"""Compose SGen's packed square switch network at NGen's identical valid/data boundary."""
from __future__ import annotations
from pathlib import Path
import re
from .model import run


def compose(rtl: Path, executable: Path, directory: Path, timeout: float) -> dict:
    text=rtl.read_text()
    pattern=r'module NGenSwitchTransposeNetwork_(\d+)\(.*?endmodule'
    networks=list(re.finditer(pattern,text,re.S))
    if not networks:
        raise ValueError('candidate has no supported unprefixed square switch networks')
    largest=max(networks,key=lambda m:int(m.group(1)))
    bits=int(largest.group(1))
    packed=re.search(r'input \[(\d+):0\] data_in',largest.group())
    width=(int(packed.group(1))+1)//(1<<bits)
    generated=directory/'sgen-permutation.v'
    process=run(['bash',str(executable),'-nologo','-n',str(2*bits),'-k',str(bits),'-hw','signed',str(width),'-o',str(generated),'switchtranspose'],directory,directory/'sgen.log',timeout)
    if process['returncode']:
        return process
    definitions='\n'.join(re.findall(r'module SGenSwitchTranspose(?:Unit|Network)_.*?endmodule',generated.read_text(),re.S))
    if not definitions:
        raise ValueError('SGen emitted no recognized switch definitions')
    def wrapper(match):
        b=int(match.group(1)); packed_width=(1<<b)*width
        return f'''module NGenSwitchTransposeNetwork_{b}(input clock,reset,valid_in,input [{packed_width-1}:0] data_in,output valid_out,output [{packed_width-1}:0] data_out);
SGenSwitchTransposeNetwork_{b}_{width} composed(clock,reset,valid_in,data_in,valid_out,data_out);
endmodule'''
    rtl.write_text(re.sub(pattern,wrapper,text,flags=re.S)+'\n// Square permutation generated by SGen; see recorded SGen source provenance.\n'+definitions+'\n')
    return {**process,'boundary':'packed valid/data, uninterrupted frames','lanes':1<<bits,'data_width':width,'latency_cycles':(1<<bits)-1}
