"""Compose SGen's packed square switch network at NGen's identical valid/data boundary."""
from __future__ import annotations
from pathlib import Path
import re
from .model import run


def compose(rtl: Path, executable: Path, directory: Path, timeout: float) -> dict:
    text=rtl.read_text()
    pattern=r'module NGenSwitchTransposeNetwork_(\d+)\(.*?endmodule'
    networks=list(re.finditer(pattern,text,re.S))
    if not networks:
        raise ValueError('candidate has no supported unprefixed square switch networks')
    largest=max(networks,key=lambda m:int(m.group(1)))
    bits=int(largest.group(1))
    packed=re.search(r'input \[(\d+):0\] data_in',largest.group())
    width=(int(packed.group(1))+1)//(1<<bits)
    generated=directory/'sgen-permutation.v'
    process=run(['bash',str(executable),'-nologo','-n',str(2*bits),'-k',str(bits),'-hw','signed',str(width),'-o',str(generated),'switchtranspose'],directory,directory/'sgen.log',timeout)
    if process['returncode']:
        return process
    definitions='\n'.join(re.findall(r'module SGenSwitchTranspose(?:Unit|Network)_.*?endmodule',generated.read_text(),re.S))
    if not definitions:
        raise ValueError('SGen emitted no recognized switch definitions')
    def wrapper(match):
        b=int(match.group(1)); packed_width=(1<<b)*width
        return f'''module NGenSwitchTransposeNetwork_{b}(input clock,reset,valid_in,input [{packed_width-1}:0] data_in,output valid_out,output [{packed_width-1}:0] data_out);
SGenSwitchTransposeNetwork_{b}_{width} composed(clock,reset,valid_in,data_in,valid_out,data_out);
endmodule'''
    rtl.write_text(re.sub(pattern,wrapper,text,flags=re.S)+'\n// Square permutation generated by SGen; see recorded SGen source provenance.\n'+definitions+'\n')
    return {**process,'boundary':'packed valid/data, uninterrupted frames','lanes':1<<bits,'data_width':width,'latency_cycles':(1<<bits)-1}


def compose_linear(rtl: Path, executable: Path, directory: Path, timeout: float) -> dict:
    """Replace square packed networks with dual-control SGen stride RAM networks.

    Delay payload to honor each generated next lead time. Frames remain
    uninterrupted; this adapter does not invent ready/valid backpressure.
    """
    import time
    started=time.monotonic();text=rtl.read_text()
    pattern=r'module NGenSwitchTransposeNetwork_(\d+)\(.*?endmodule'
    networks=list(re.finditer(pattern,text,re.S))
    if not networks:raise ValueError('no supported square packed network')
    components=[];replacements={};definitions=[]
    for match in networks:
        bits=int(match.group(1));lanes=1<<bits
        packed=re.search(r'input \[(\d+):0\] data_in',match.group())
        total=int(packed.group(1))+1;width=total//lanes
        work=directory/f'sgen-linear-{bits}';work.mkdir(exist_ok=True)
        generated=work/'stride.v'
        process=run(['bash',str(executable),'-nologo','-n',str(2*bits),'-k',str(bits),'-r',str(bits),'-hw','signed',str(width),'-dualRAMcontrol','-o',str(generated),'stride'],work,work/'generation.log',max(0,timeout-(time.monotonic()-started)))
        if process['returncode']:return {**process,'components':components}
        source=generated.read_text()
        lead_match=re.search(r'set high (\d+) cycles before the first inputs enter',source)
        if not lead_match:raise ValueError('missing SGen next lead declaration')
        lead=int(lead_match.group(1))
        names=re.findall(r'\bmodule\s+(\w+)',source)
        for name in sorted(set(names),key=len,reverse=True):
            source=re.sub(r'\b'+re.escape(name)+r'\b',f'SGenLinear_{bits}_{width}_{name}',source)
        definitions.append(source)
        ports=['.clk(clock)','.reset(reset)','.next(valid_in && input_count==0)','.next_out(core_next_out)']
        ports += [f'.i{i}(core_input[{i*width}+:{width}])' for i in range(lanes)]
        ports += [f'.o{i}(data_out[{i*width}+:{width}])' for i in range(lanes)]
        delay_decl=f'reg [{total-1}:0] payload_delay [0:{lead-1}];integer delay_index;' if lead else ''
        delay_update=f'payload_delay[0]<=data_in;for(delay_index=1;delay_index<{lead};delay_index=delay_index+1)payload_delay[delay_index]<=payload_delay[delay_index-1];' if lead else ''
        replacements[bits]=f'''module NGenSwitchTransposeNetwork_{bits}(input clock,reset,valid_in,input [{total-1}:0] data_in,output valid_out,output [{total-1}:0] data_out);
integer input_count,output_remaining;wire core_next_out;
{delay_decl}
wire [{total-1}:0] core_input={f'payload_delay[{lead-1}]' if lead else 'data_in'};
assign valid_out=core_next_out || output_remaining>0;
always @(posedge clock)begin
 {delay_update}
 if(reset)begin input_count<=0;output_remaining<=0;end
 else begin
  if(valid_in)begin if(input_count=={lanes-1})input_count<=0;else input_count<=input_count+1;end
  if(core_next_out)output_remaining<={lanes-1};else if(output_remaining>0)output_remaining<=output_remaining-1;
 end
end
SGenLinear_{bits}_{width}_main core({','.join(ports)});
endmodule'''
        components.append({'bits':bits,'lanes':lanes,'data_width':width,'next_lead_cycles':lead,'process':process})
    rtl.write_text(re.sub(pattern,lambda m:replacements[int(m.group(1))],text,flags=re.S)+'\n'+'\n'.join(definitions))
    return {'returncode':0,'seconds':time.monotonic()-started,'components':components,'boundary':'packed valid/data, uninterrupted frames; payload lead adapter included','implementation':'SGen dual-control stride RAM network'}
