// Generated by scripts/generate_small_ntt_rtl.py.
// Fixed-size synthesizable RTL reference for small NTT metric tasks.
// YATA datapath follows the RAINTT SREDC modular reduction style and intentionally avoids modulo operators.

module SmallYata8RainttP27Rtl(
  input clock,
  input reset,
  input io_intt_validin,
  input [31:0] io_intt_in_0,
  input [31:0] io_intt_in_1,
  input [31:0] io_intt_in_2,
  input [31:0] io_intt_in_3,
  input [31:0] io_intt_in_4,
  input [31:0] io_intt_in_5,
  input [31:0] io_intt_in_6,
  input [31:0] io_intt_in_7,
  output reg [26:0] io_intt_out_0,
  output reg [26:0] io_intt_out_1,
  output reg [26:0] io_intt_out_2,
  output reg [26:0] io_intt_out_3,
  output reg [26:0] io_intt_out_4,
  output reg [26:0] io_intt_out_5,
  output reg [26:0] io_intt_out_6,
  output reg [26:0] io_intt_out_7,
  output reg io_intt_validout,
  input io_ntt_validin,
  input [26:0] io_ntt_in_0,
  input [26:0] io_ntt_in_1,
  input [26:0] io_ntt_in_2,
  input [26:0] io_ntt_in_3,
  input [26:0] io_ntt_in_4,
  input [26:0] io_ntt_in_5,
  input [26:0] io_ntt_in_6,
  input [26:0] io_ntt_in_7,
  output reg [31:0] io_ntt_out_0,
  output reg [31:0] io_ntt_out_1,
  output reg [31:0] io_ntt_out_2,
  output reg [31:0] io_ntt_out_3,
  output reg [31:0] io_ntt_out_4,
  output reg [31:0] io_ntt_out_5,
  output reg [31:0] io_ntt_out_6,
  output reg [31:0] io_ntt_out_7,
  output reg io_ntt_validout
);
    localparam integer YATA_N = 8;
    localparam integer YATA_CYCLES = 1;
    localparam signed [53:0] YATA_P = 54'sd40960001;
    localparam signed [63:0] YATA_MODSWITCH_SCALE = 64'sd7036874245;

    reg [31:0] intt_in_buf [0:YATA_N-1];
    reg signed [26:0] intt_out_buf [0:YATA_N-1];
    reg signed [26:0] ntt_in_buf [0:YATA_N-1];
    reg [31:0] ntt_out_buf [0:YATA_N-1];
    reg signed [53:0] work [0:YATA_N-1];
    reg [3:0] intt_in_count;
    reg [3:0] ntt_in_count;
    reg [3:0] intt_out_count;
    reg [3:0] ntt_out_count;
    reg intt_output_active;
    reg ntt_output_active;
    reg signed [53:0] temp;
    reg signed [26:0] mulres;
    reg [63:0] posres;
    reg [95:0] scaled;
    integer i;

    function automatic signed [26:0] yata_sword(input signed [53:0] x);
      begin
        yata_sword = x[26:0];
      end
    endfunction

    function automatic signed [26:0] yata_add_mod(input signed [53:0] a, input signed [53:0] b);
      reg signed [53:0] add;
      begin
        add = a + b;
        if (add >= YATA_P) yata_add_mod = add - YATA_P;
        else if (add <= -YATA_P) yata_add_mod = add + YATA_P;
        else yata_add_mod = add;
      end
    endfunction

    function automatic signed [26:0] yata_sub_mod(input signed [53:0] a, input signed [53:0] b);
      reg signed [53:0] sub;
      begin
        sub = a - b;
        if (sub >= YATA_P) yata_sub_mod = sub - YATA_P;
        else if (sub <= -YATA_P) yata_sub_mod = sub + YATA_P;
        else yata_sub_mod = sub;
      end
    endfunction

    function automatic signed [26:0] yata_sredc(input signed [53:0] a);
      reg [26:0] a0;
      reg signed [26:0] a1;
      reg signed [26:0] m;
      reg signed [26:0] t1;
      reg signed [53:0] m_wide;
      reg signed [53:0] t1_wide;
      begin
        a0 = a[26:0];
        a1 = a[53:27];
        m_wide = -(({27'd0, a0} * 54'sd625) <<< 16) + {27'd0, a0};
        m = m_wide[26:0];
        t1_wide = (($signed(m) * 54'sd625) <<< 16) + $signed(m);
        t1 = t1_wide[53:27];
        yata_sredc = a1 - t1;
      end
    endfunction

    function automatic signed [26:0] yata_mul_sredc(input signed [26:0] a, input signed [26:0] b);
      begin
        yata_mul_sredc = yata_sredc($signed(a) * $signed(b));
      end
    endfunction

    function automatic signed [53:0] yata_const_twiddle_mul(input signed [53:0] a, input integer radixbit, input integer num);
      begin
        if (radixbit == 2 && num == 1) yata_const_twiddle_mul = (a * 25) <<< 8;
        else if (radixbit == 3 && num == 1) yata_const_twiddle_mul = (a * 5) <<< 4;
        else if (radixbit == 3 && num == 2) yata_const_twiddle_mul = (a * 25) <<< 8;
        else if (radixbit == 3 && num == 3) yata_const_twiddle_mul = (a * 125) <<< 12;
        else yata_const_twiddle_mul = a;
      end
    endfunction

    task automatic compute_intt;
      begin
        work[0] = yata_mul_sredc(intt_in_buf[0][26:0], 27'sd11337725);
work[1] = yata_mul_sredc(intt_in_buf[1][26:0], 27'sd36471443);
work[2] = yata_mul_sredc(intt_in_buf[2][26:0], 27'sd5897978);
work[3] = yata_mul_sredc(intt_in_buf[3][26:0], 27'sd9555369);
work[4] = yata_mul_sredc(intt_in_buf[4][26:0], 27'sd21278229);
work[5] = yata_mul_sredc(intt_in_buf[5][26:0], 27'sd27149502);
work[6] = yata_mul_sredc(intt_in_buf[6][26:0], 27'sd22898279);
work[7] = yata_mul_sredc(intt_in_buf[7][26:0], 27'sd1080107);
temp = yata_sword(work[0]);
work[0] = yata_add_mod(work[0], work[4]);
work[4] = temp - work[4];
temp = yata_sword(work[1]);
work[1] = yata_add_mod(work[1], work[5]);
work[5] = temp - work[5];
temp = yata_sword(work[2]);
work[2] = yata_add_mod(work[2], work[6]);
work[6] = temp - work[6];
temp = yata_sword(work[3]);
work[3] = yata_add_mod(work[3], work[7]);
work[7] = temp - work[7];
temp = yata_sword(work[0]);
work[0] = yata_add_mod(work[0], work[2]);
work[2] = temp - work[2];
temp = yata_sword(work[1]);
work[1] = yata_add_mod(work[1], work[3]);
work[3] = temp - work[3];
temp = yata_sword(work[0]);
work[0] = yata_add_mod(work[0], work[1]);
work[1] = yata_sub_mod(temp, work[1]);
work[3] = yata_const_twiddle_mul(work[3], 2, 1);
temp = work[2];
work[2] = yata_sredc(work[2] + work[3]);
work[3] = yata_sredc(temp - work[3]);
work[6] = yata_const_twiddle_mul(work[6], 3, 2);
temp = work[4];
work[4] = work[4] + work[6];
work[6] = temp - work[6];
temp = yata_const_twiddle_mul(work[5], 3, 3);
work[5] = yata_const_twiddle_mul(work[5], 3, 1) + yata_const_twiddle_mul(work[7], 3, 3);
work[7] = temp + yata_const_twiddle_mul(work[7], 3, 1);
temp = work[4];
work[4] = yata_sredc(work[4] + work[5]);
work[5] = yata_sredc(temp - work[5]);
temp = work[6];
work[6] = yata_sredc(work[6] + work[7]);
work[7] = yata_sredc(temp - work[7]);
        for (i = 0; i < YATA_N; i = i + 1) intt_out_buf[i] <= work[i][26:0];
      end
    endtask

    task automatic compute_ntt;
      begin
        work[0] = $signed(ntt_in_buf[0]);
work[1] = $signed(ntt_in_buf[1]);
work[2] = $signed(ntt_in_buf[2]);
work[3] = $signed(ntt_in_buf[3]);
work[4] = $signed(ntt_in_buf[4]);
work[5] = $signed(ntt_in_buf[5]);
work[6] = $signed(ntt_in_buf[6]);
work[7] = $signed(ntt_in_buf[7]);
temp = yata_sword(work[0]);
work[0] = yata_add_mod(work[0], work[1]);
work[1] = yata_sub_mod(temp, work[1]);
temp = yata_sword(work[2]);
work[2] = yata_add_mod(work[2], work[3]);
work[3] = yata_sub_mod(temp, work[3]);
temp = work[0];
work[0] = yata_add_mod(work[0], work[2]);
work[2] = yata_sub_mod(temp, work[2]);
temp = work[1];
work[3] = -yata_const_twiddle_mul(work[3], 2, 1);
work[1] = work[1] + work[3];
work[3] = temp - work[3];
temp = yata_sword(work[4]);
work[4] = yata_add_mod(work[4], work[5]);
work[5] = yata_sub_mod(temp, work[5]);
temp = yata_sword(work[6]);
work[6] = yata_add_mod(work[6], work[7]);
work[7] = yata_sub_mod(temp, work[7]);
temp = work[4];
work[4] = yata_add_mod(work[4], work[6]);
work[6] = -yata_const_twiddle_mul(temp - work[6], 3, 2);
temp = -yata_const_twiddle_mul(work[5], 3, 1);
work[5] = -yata_const_twiddle_mul(work[5], 3, 3) - yata_const_twiddle_mul(work[7], 3, 1);
work[7] = temp - yata_const_twiddle_mul(work[7], 3, 3);
temp = yata_sword(work[0]);
work[0] = yata_add_mod(work[0], work[4]);
work[4] = yata_sub_mod(temp, work[4]);
temp = work[1];
work[1] = yata_sredc(work[1] + work[5]);
work[5] = yata_sredc(temp - work[5]);
temp = work[2];
work[2] = yata_sredc(work[2] + work[6]);
work[6] = yata_sredc(temp - work[6]);
temp = work[3];
work[3] = yata_sredc(work[3] + work[7]);
work[7] = yata_sredc(temp - work[7]);
        mulres = yata_mul_sredc(yata_sword(work[0]), 27'sd16777216);
        posres = (mulres < 0) ? (mulres + YATA_P) : mulres;
        scaled = ((posres * YATA_MODSWITCH_SCALE) + 96'd33554432) >> 26;
        ntt_out_buf[0] <= scaled[31:0];
        mulres = yata_mul_sredc(yata_sword(work[1]), 27'sd7520300);
        posres = (mulres < 0) ? (mulres + YATA_P) : mulres;
        scaled = ((posres * YATA_MODSWITCH_SCALE) + 96'd33554432) >> 26;
        ntt_out_buf[1] <= scaled[31:0];
        mulres = yata_mul_sredc(yata_sword(work[2]), 27'sd6167871);
        posres = (mulres < 0) ? (mulres + YATA_P) : mulres;
        scaled = ((posres * YATA_MODSWITCH_SCALE) + 96'd33554432) >> 26;
        ntt_out_buf[2] <= scaled[31:0];
        mulres = yata_mul_sredc(yata_sword(work[3]), 27'sd10334004);
        posres = (mulres < 0) ? (mulres + YATA_P) : mulres;
        scaled = ((posres * YATA_MODSWITCH_SCALE) + 96'd33554432) >> 26;
        ntt_out_buf[3] <= scaled[31:0];
        mulres = yata_mul_sredc(yata_sword(work[4]), 27'sd22940222);
        posres = (mulres < 0) ? (mulres + YATA_P) : mulres;
        scaled = ((posres * YATA_MODSWITCH_SCALE) + 96'd33554432) >> 26;
        ntt_out_buf[4] <= scaled[31:0];
        mulres = yata_mul_sredc(yata_sword(work[5]), 27'sd39041176);
        posres = (mulres < 0) ? (mulres + YATA_P) : mulres;
        scaled = ((posres * YATA_MODSWITCH_SCALE) + 96'd33554432) >> 26;
        ntt_out_buf[5] <= scaled[31:0];
        mulres = yata_mul_sredc(yata_sword(work[6]), 27'sd11066564);
        posres = (mulres < 0) ? (mulres + YATA_P) : mulres;
        scaled = ((posres * YATA_MODSWITCH_SCALE) + 96'd33554432) >> 26;
        ntt_out_buf[6] <= scaled[31:0];
        mulres = yata_mul_sredc(yata_sword(work[7]), 27'sd12776015);
        posres = (mulres < 0) ? (mulres + YATA_P) : mulres;
        scaled = ((posres * YATA_MODSWITCH_SCALE) + 96'd33554432) >> 26;
        ntt_out_buf[7] <= scaled[31:0];
  end
endtask

always @(posedge clock) begin
  if (reset) begin
    io_intt_validout <= 1'b0;
    io_ntt_validout <= 1'b0;
    intt_in_count <= 4'd0;
    ntt_in_count <= 4'd0;
    intt_out_count <= 4'd0;
    ntt_out_count <= 4'd0;
    intt_output_active <= 1'b0;
    ntt_output_active <= 1'b0;
    for (i = 0; i < YATA_N; i = i + 1) begin
      intt_in_buf[i] <= 32'd0;
      intt_out_buf[i] <= 27'sd0;
      ntt_in_buf[i] <= 27'sd0;
      ntt_out_buf[i] <= 32'd0;
    end
  end else begin
    io_intt_validout <= 1'b0;
    io_ntt_validout <= 1'b0;

    if (intt_output_active) begin
      io_intt_validout <= 1'b1;
        io_intt_out_0 <= intt_out_buf[intt_out_count * 8 + 0];
        io_intt_out_1 <= intt_out_buf[intt_out_count * 8 + 1];
        io_intt_out_2 <= intt_out_buf[intt_out_count * 8 + 2];
        io_intt_out_3 <= intt_out_buf[intt_out_count * 8 + 3];
        io_intt_out_4 <= intt_out_buf[intt_out_count * 8 + 4];
        io_intt_out_5 <= intt_out_buf[intt_out_count * 8 + 5];
        io_intt_out_6 <= intt_out_buf[intt_out_count * 8 + 6];
        io_intt_out_7 <= intt_out_buf[intt_out_count * 8 + 7];
  if (intt_out_count == YATA_CYCLES - 1) begin
    intt_output_active <= 1'b0;
    intt_out_count <= 4'd0;
  end else begin
    intt_out_count <= intt_out_count + 1'b1;
  end
end

if (ntt_output_active) begin
  io_ntt_validout <= 1'b1;
        io_ntt_out_0 <= ntt_out_buf[0 * YATA_CYCLES + ntt_out_count];
        io_ntt_out_1 <= ntt_out_buf[1 * YATA_CYCLES + ntt_out_count];
        io_ntt_out_2 <= ntt_out_buf[2 * YATA_CYCLES + ntt_out_count];
        io_ntt_out_3 <= ntt_out_buf[3 * YATA_CYCLES + ntt_out_count];
        io_ntt_out_4 <= ntt_out_buf[4 * YATA_CYCLES + ntt_out_count];
        io_ntt_out_5 <= ntt_out_buf[5 * YATA_CYCLES + ntt_out_count];
        io_ntt_out_6 <= ntt_out_buf[6 * YATA_CYCLES + ntt_out_count];
        io_ntt_out_7 <= ntt_out_buf[7 * YATA_CYCLES + ntt_out_count];
  if (ntt_out_count == YATA_CYCLES - 1) begin
    ntt_output_active <= 1'b0;
    ntt_out_count <= 4'd0;
  end else begin
    ntt_out_count <= ntt_out_count + 1'b1;
  end
end

if (io_intt_validin) begin
        intt_in_buf[0 * YATA_CYCLES + intt_in_count] = io_intt_in_0;
        intt_in_buf[1 * YATA_CYCLES + intt_in_count] = io_intt_in_1;
        intt_in_buf[2 * YATA_CYCLES + intt_in_count] = io_intt_in_2;
        intt_in_buf[3 * YATA_CYCLES + intt_in_count] = io_intt_in_3;
        intt_in_buf[4 * YATA_CYCLES + intt_in_count] = io_intt_in_4;
        intt_in_buf[5 * YATA_CYCLES + intt_in_count] = io_intt_in_5;
        intt_in_buf[6 * YATA_CYCLES + intt_in_count] = io_intt_in_6;
        intt_in_buf[7 * YATA_CYCLES + intt_in_count] = io_intt_in_7;
  if (intt_in_count == YATA_CYCLES - 1) begin
    intt_in_count <= 4'd0;
    compute_intt();
    intt_output_active <= 1'b1;
    intt_out_count <= 4'd0;
  end else begin
    intt_in_count <= intt_in_count + 1'b1;
  end
end

if (io_ntt_validin) begin
        ntt_in_buf[ntt_in_count * 8 + 0] = io_ntt_in_0;
        ntt_in_buf[ntt_in_count * 8 + 1] = io_ntt_in_1;
        ntt_in_buf[ntt_in_count * 8 + 2] = io_ntt_in_2;
        ntt_in_buf[ntt_in_count * 8 + 3] = io_ntt_in_3;
        ntt_in_buf[ntt_in_count * 8 + 4] = io_ntt_in_4;
        ntt_in_buf[ntt_in_count * 8 + 5] = io_ntt_in_5;
        ntt_in_buf[ntt_in_count * 8 + 6] = io_ntt_in_6;
        ntt_in_buf[ntt_in_count * 8 + 7] = io_ntt_in_7;
        if (ntt_in_count == YATA_CYCLES - 1) begin
          ntt_in_count <= 4'd0;
          compute_ntt();
          ntt_output_active <= 1'b1;
          ntt_out_count <= 4'd0;
        end else begin
          ntt_in_count <= ntt_in_count + 1'b1;
        end
      end
    end
  end
endmodule
