// Generated by scripts/generate_small_ntt_rtl.py.
// Fixed-size synthesizable RTL reference for small NTT metric tasks.
// HOGE32 is a radix-32 butterfly block from the 1024-point HOGE NTT decomposition.

module SmallHoge32P64Rtl(
  input clock,
  input reset,
  input io_intt_validin,
  input [63:0] io_intt_in_0,
  input [63:0] io_intt_in_1,
  input [63:0] io_intt_in_2,
  input [63:0] io_intt_in_3,
  input [63:0] io_intt_in_4,
  input [63:0] io_intt_in_5,
  input [63:0] io_intt_in_6,
  input [63:0] io_intt_in_7,
  input [63:0] io_intt_in_8,
  input [63:0] io_intt_in_9,
  input [63:0] io_intt_in_10,
  input [63:0] io_intt_in_11,
  input [63:0] io_intt_in_12,
  input [63:0] io_intt_in_13,
  input [63:0] io_intt_in_14,
  input [63:0] io_intt_in_15,
  input [63:0] io_intt_in_16,
  input [63:0] io_intt_in_17,
  input [63:0] io_intt_in_18,
  input [63:0] io_intt_in_19,
  input [63:0] io_intt_in_20,
  input [63:0] io_intt_in_21,
  input [63:0] io_intt_in_22,
  input [63:0] io_intt_in_23,
  input [63:0] io_intt_in_24,
  input [63:0] io_intt_in_25,
  input [63:0] io_intt_in_26,
  input [63:0] io_intt_in_27,
  input [63:0] io_intt_in_28,
  input [63:0] io_intt_in_29,
  input [63:0] io_intt_in_30,
  input [63:0] io_intt_in_31,
  output reg [63:0] io_intt_out_0,
  output reg [63:0] io_intt_out_1,
  output reg [63:0] io_intt_out_2,
  output reg [63:0] io_intt_out_3,
  output reg [63:0] io_intt_out_4,
  output reg [63:0] io_intt_out_5,
  output reg [63:0] io_intt_out_6,
  output reg [63:0] io_intt_out_7,
  output reg [63:0] io_intt_out_8,
  output reg [63:0] io_intt_out_9,
  output reg [63:0] io_intt_out_10,
  output reg [63:0] io_intt_out_11,
  output reg [63:0] io_intt_out_12,
  output reg [63:0] io_intt_out_13,
  output reg [63:0] io_intt_out_14,
  output reg [63:0] io_intt_out_15,
  output reg [63:0] io_intt_out_16,
  output reg [63:0] io_intt_out_17,
  output reg [63:0] io_intt_out_18,
  output reg [63:0] io_intt_out_19,
  output reg [63:0] io_intt_out_20,
  output reg [63:0] io_intt_out_21,
  output reg [63:0] io_intt_out_22,
  output reg [63:0] io_intt_out_23,
  output reg [63:0] io_intt_out_24,
  output reg [63:0] io_intt_out_25,
  output reg [63:0] io_intt_out_26,
  output reg [63:0] io_intt_out_27,
  output reg [63:0] io_intt_out_28,
  output reg [63:0] io_intt_out_29,
  output reg [63:0] io_intt_out_30,
  output reg [63:0] io_intt_out_31,
output reg io_intt_validout,
input io_ntt_validin,
  input [63:0] io_ntt_in_0,
  input [63:0] io_ntt_in_1,
  input [63:0] io_ntt_in_2,
  input [63:0] io_ntt_in_3,
  input [63:0] io_ntt_in_4,
  input [63:0] io_ntt_in_5,
  input [63:0] io_ntt_in_6,
  input [63:0] io_ntt_in_7,
  input [63:0] io_ntt_in_8,
  input [63:0] io_ntt_in_9,
  input [63:0] io_ntt_in_10,
  input [63:0] io_ntt_in_11,
  input [63:0] io_ntt_in_12,
  input [63:0] io_ntt_in_13,
  input [63:0] io_ntt_in_14,
  input [63:0] io_ntt_in_15,
  input [63:0] io_ntt_in_16,
  input [63:0] io_ntt_in_17,
  input [63:0] io_ntt_in_18,
  input [63:0] io_ntt_in_19,
  input [63:0] io_ntt_in_20,
  input [63:0] io_ntt_in_21,
  input [63:0] io_ntt_in_22,
  input [63:0] io_ntt_in_23,
  input [63:0] io_ntt_in_24,
  input [63:0] io_ntt_in_25,
  input [63:0] io_ntt_in_26,
  input [63:0] io_ntt_in_27,
  input [63:0] io_ntt_in_28,
  input [63:0] io_ntt_in_29,
  input [63:0] io_ntt_in_30,
  input [63:0] io_ntt_in_31,
  output reg [63:0] io_ntt_out_0,
  output reg [63:0] io_ntt_out_1,
  output reg [63:0] io_ntt_out_2,
  output reg [63:0] io_ntt_out_3,
  output reg [63:0] io_ntt_out_4,
  output reg [63:0] io_ntt_out_5,
  output reg [63:0] io_ntt_out_6,
  output reg [63:0] io_ntt_out_7,
  output reg [63:0] io_ntt_out_8,
  output reg [63:0] io_ntt_out_9,
  output reg [63:0] io_ntt_out_10,
  output reg [63:0] io_ntt_out_11,
  output reg [63:0] io_ntt_out_12,
  output reg [63:0] io_ntt_out_13,
  output reg [63:0] io_ntt_out_14,
  output reg [63:0] io_ntt_out_15,
  output reg [63:0] io_ntt_out_16,
  output reg [63:0] io_ntt_out_17,
  output reg [63:0] io_ntt_out_18,
  output reg [63:0] io_ntt_out_19,
  output reg [63:0] io_ntt_out_20,
  output reg [63:0] io_ntt_out_21,
  output reg [63:0] io_ntt_out_22,
  output reg [63:0] io_ntt_out_23,
  output reg [63:0] io_ntt_out_24,
  output reg [63:0] io_ntt_out_25,
  output reg [63:0] io_ntt_out_26,
  output reg [63:0] io_ntt_out_27,
  output reg [63:0] io_ntt_out_28,
  output reg [63:0] io_ntt_out_29,
  output reg [63:0] io_ntt_out_30,
  output reg [63:0] io_ntt_out_31,
  output reg io_ntt_validout
);
  localparam [63:0] HOGE_P = 64'hffffffff00000001;

  reg [63:0] intt_in_buf [0:31];
  reg [63:0] intt_out_buf [0:31];
  reg [63:0] ntt_in_buf [0:31];
  reg [63:0] ntt_out_buf [0:31];
  reg intt_pending;
  reg ntt_pending;
  reg [63:0] work [0:31];
  reg [63:0] temp;
  integer i;

  function automatic [63:0] hoge_normalize(input [63:0] value);
    begin
      hoge_normalize = (value >= HOGE_P) ? value + 64'h00000000ffffffff : value;
    end
  endfunction

  function automatic [63:0] hoge_add(input [63:0] left, input [63:0] right);
    reg [64:0] sum;
    begin
      sum = {1'b0, left} + {1'b0, right};
      hoge_add = (sum[64] || sum[63:0] >= HOGE_P) ? sum[63:0] + 64'h00000000ffffffff : sum[63:0];
    end
  endfunction

  function automatic [63:0] hoge_sub(input [63:0] left, input [63:0] right);
    reg [64:0] diff;
    begin
      diff = {1'b0, left} - {1'b0, right};
      hoge_sub = diff[64] ? diff[63:0] - 64'h00000000ffffffff : diff[63:0];
    end
  endfunction

  function automatic [63:0] hoge_low32(input [63:0] value);
    begin
      hoge_low32 = {32'd0, value[31:0]};
    end
  endfunction

  function automatic [63:0] hoge_lshift(input [63:0] value, input integer shift);
    reg [63:0] templ;
    reg [63:0] tempul;
    reg [63:0] tempuu;
    reg [63:0] tempu;
    reg [63:0] res;
    begin
      if (shift == 0) begin
        hoge_lshift = value;
      end else if (shift < 32) begin
        templ = value << shift;
        tempu = value >> (64 - shift);
        res = templ + (tempu << 32) - tempu;
        if (res < templ) res = res + 64'h00000000ffffffff;
        hoge_lshift = hoge_normalize(res);
      end else if (shift == 32) begin
        templ = value << shift;
        tempul = hoge_low32(value >> (64 - shift));
        res = templ + (tempul << 32) - tempul;
        if ((res > templ) && (tempul == 0)) res = res - 64'h00000000ffffffff;
        if ((res < templ) && (tempul != 0)) res = res + 64'h00000000ffffffff;
        hoge_lshift = hoge_normalize(res);
      end else if (shift < 64) begin
        templ = hoge_low32(value << (shift - 32));
        tempul = hoge_low32(value >> (64 - shift));
        tempuu = value >> (96 - shift);
        res = ((templ + tempul) << 32) - tempuu - tempul;
        if ((res > (templ << 32)) && (tempul == 0)) res = res - 64'h00000000ffffffff;
        if ((res < (templ << 32)) && (tempul != 0)) res = res + 64'h00000000ffffffff;
        hoge_lshift = hoge_normalize(res);
      end else if (shift == 64) begin
        templ = hoge_low32(value);
        templ = (templ << 32) - templ;
        tempu = value >> (96 - shift);
        res = templ - tempu;
        if (res > templ) res = res - 64'h00000000ffffffff;
        hoge_lshift = hoge_normalize(res);
      end else if (shift < 96) begin
        templ = hoge_low32(value << (shift - 64));
        templ = (templ << 32) - templ;
        tempu = value >> (96 - shift);
        res = templ - tempu;
        if (res > templ) res = res - 64'h00000000ffffffff;
        hoge_lshift = hoge_normalize(res);
      end else if (shift == 96) begin
        hoge_lshift = hoge_sub(HOGE_P, value);
      end else if (shift < 128) begin
        templ = value << (shift - 96);
        tempu = value >> (160 - shift);
        res = templ + (tempu << 32) - tempu;
        if (res < templ) res = res + 64'h00000000ffffffff;
        hoge_lshift = hoge_sub(HOGE_P, hoge_normalize(res));
      end else if (shift == 128) begin
        templ = hoge_low32(value);
        tempul = hoge_low32(value >> (160 - shift));
        res = hoge_sub(tempul, templ << 32);
        hoge_lshift = hoge_sub(res, tempul << 32);
      end else if (shift < 160) begin
        templ = hoge_low32(value << (shift - 128));
        tempul = hoge_low32(value >> (160 - shift));
        tempuu = value >> (192 - shift);
        res = hoge_sub(tempul + tempuu, templ << 32);
        hoge_lshift = hoge_sub(res, tempul << 32);
      end else if (shift == 160) begin
        templ = hoge_low32(value);
        tempu = value >> (192 - shift);
        hoge_lshift = hoge_sub(templ + tempu, templ << 32);
      end else begin
        templ = hoge_low32(value << (shift - 160));
        tempu = value >> (192 - shift);
        res = templ + tempu - (templ << 32);
        if (res > tempu) res = res - 64'h00000000ffffffff;
        hoge_lshift = hoge_normalize(res);
      end
    end
  endfunction

  task automatic compute_intt;
    begin
      for (i = 0; i < 32; i = i + 1) work[i] = intt_in_buf[i];
      temp = work[0];
      work[0] = hoge_add(work[0], work[16]);
      work[16] = hoge_sub(temp, work[16]);
      temp = work[1];
      work[1] = hoge_add(work[1], work[17]);
      work[17] = hoge_sub(temp, work[17]);
      temp = work[2];
      work[2] = hoge_add(work[2], work[18]);
      work[18] = hoge_sub(temp, work[18]);
      temp = work[3];
      work[3] = hoge_add(work[3], work[19]);
      work[19] = hoge_sub(temp, work[19]);
      temp = work[4];
      work[4] = hoge_add(work[4], work[20]);
      work[20] = hoge_sub(temp, work[20]);
      temp = work[5];
      work[5] = hoge_add(work[5], work[21]);
      work[21] = hoge_sub(temp, work[21]);
      temp = work[6];
      work[6] = hoge_add(work[6], work[22]);
      work[22] = hoge_sub(temp, work[22]);
      temp = work[7];
      work[7] = hoge_add(work[7], work[23]);
      work[23] = hoge_sub(temp, work[23]);
      temp = work[8];
      work[8] = hoge_add(work[8], work[24]);
      work[24] = hoge_sub(temp, work[24]);
      temp = work[9];
      work[9] = hoge_add(work[9], work[25]);
      work[25] = hoge_sub(temp, work[25]);
      temp = work[10];
      work[10] = hoge_add(work[10], work[26]);
      work[26] = hoge_sub(temp, work[26]);
      temp = work[11];
      work[11] = hoge_add(work[11], work[27]);
      work[27] = hoge_sub(temp, work[27]);
      temp = work[12];
      work[12] = hoge_add(work[12], work[28]);
      work[28] = hoge_sub(temp, work[28]);
      temp = work[13];
      work[13] = hoge_add(work[13], work[29]);
      work[29] = hoge_sub(temp, work[29]);
      temp = work[14];
      work[14] = hoge_add(work[14], work[30]);
      work[30] = hoge_sub(temp, work[30]);
      temp = work[15];
      work[15] = hoge_add(work[15], work[31]);
      work[31] = hoge_sub(temp, work[31]);
      work[17] = hoge_lshift(work[17], 6);
      work[18] = hoge_lshift(work[18], 12);
      work[19] = hoge_lshift(work[19], 18);
      work[20] = hoge_lshift(work[20], 24);
      work[21] = hoge_lshift(work[21], 30);
      work[22] = hoge_lshift(work[22], 36);
      work[23] = hoge_lshift(work[23], 42);
      work[24] = hoge_lshift(work[24], 48);
      work[25] = hoge_lshift(work[25], 54);
      work[26] = hoge_lshift(work[26], 60);
      work[27] = hoge_lshift(work[27], 66);
      work[28] = hoge_lshift(work[28], 72);
      work[29] = hoge_lshift(work[29], 78);
      work[30] = hoge_lshift(work[30], 84);
      work[31] = hoge_lshift(work[31], 90);
      temp = work[0];
      work[0] = hoge_add(work[0], work[8]);
      work[8] = hoge_sub(temp, work[8]);
      temp = work[1];
      work[1] = hoge_add(work[1], work[9]);
      work[9] = hoge_sub(temp, work[9]);
      temp = work[2];
      work[2] = hoge_add(work[2], work[10]);
      work[10] = hoge_sub(temp, work[10]);
      temp = work[3];
      work[3] = hoge_add(work[3], work[11]);
      work[11] = hoge_sub(temp, work[11]);
      temp = work[4];
      work[4] = hoge_add(work[4], work[12]);
      work[12] = hoge_sub(temp, work[12]);
      temp = work[5];
      work[5] = hoge_add(work[5], work[13]);
      work[13] = hoge_sub(temp, work[13]);
      temp = work[6];
      work[6] = hoge_add(work[6], work[14]);
      work[14] = hoge_sub(temp, work[14]);
      temp = work[7];
      work[7] = hoge_add(work[7], work[15]);
      work[15] = hoge_sub(temp, work[15]);
      work[9] = hoge_lshift(work[9], 12);
      work[10] = hoge_lshift(work[10], 24);
      work[11] = hoge_lshift(work[11], 36);
      work[12] = hoge_lshift(work[12], 48);
      work[13] = hoge_lshift(work[13], 60);
      work[14] = hoge_lshift(work[14], 72);
      work[15] = hoge_lshift(work[15], 84);
      temp = work[0];
      work[0] = hoge_add(work[0], work[4]);
      work[4] = hoge_sub(temp, work[4]);
      temp = work[1];
      work[1] = hoge_add(work[1], work[5]);
      work[5] = hoge_sub(temp, work[5]);
      temp = work[2];
      work[2] = hoge_add(work[2], work[6]);
      work[6] = hoge_sub(temp, work[6]);
      temp = work[3];
      work[3] = hoge_add(work[3], work[7]);
      work[7] = hoge_sub(temp, work[7]);
      work[5] = hoge_lshift(work[5], 24);
      work[6] = hoge_lshift(work[6], 48);
      work[7] = hoge_lshift(work[7], 72);
      temp = work[0];
      work[0] = hoge_add(work[0], work[2]);
      work[2] = hoge_sub(temp, work[2]);
      temp = work[1];
      work[1] = hoge_add(work[1], work[3]);
      work[3] = hoge_sub(temp, work[3]);
      work[3] = hoge_lshift(work[3], 48);
      temp = work[0];
      work[0] = hoge_add(work[0], work[1]);
      work[1] = hoge_sub(temp, work[1]);
      temp = work[2];
      work[2] = hoge_add(work[2], work[3]);
      work[3] = hoge_sub(temp, work[3]);
      temp = work[4];
      work[4] = hoge_add(work[4], work[6]);
      work[6] = hoge_sub(temp, work[6]);
      temp = work[5];
      work[5] = hoge_add(work[5], work[7]);
      work[7] = hoge_sub(temp, work[7]);
      work[7] = hoge_lshift(work[7], 48);
      temp = work[4];
      work[4] = hoge_add(work[4], work[5]);
      work[5] = hoge_sub(temp, work[5]);
      temp = work[6];
      work[6] = hoge_add(work[6], work[7]);
      work[7] = hoge_sub(temp, work[7]);
      temp = work[8];
      work[8] = hoge_add(work[8], work[12]);
      work[12] = hoge_sub(temp, work[12]);
      temp = work[9];
      work[9] = hoge_add(work[9], work[13]);
      work[13] = hoge_sub(temp, work[13]);
      temp = work[10];
      work[10] = hoge_add(work[10], work[14]);
      work[14] = hoge_sub(temp, work[14]);
      temp = work[11];
      work[11] = hoge_add(work[11], work[15]);
      work[15] = hoge_sub(temp, work[15]);
      work[13] = hoge_lshift(work[13], 24);
      work[14] = hoge_lshift(work[14], 48);
      work[15] = hoge_lshift(work[15], 72);
      temp = work[8];
      work[8] = hoge_add(work[8], work[10]);
      work[10] = hoge_sub(temp, work[10]);
      temp = work[9];
      work[9] = hoge_add(work[9], work[11]);
      work[11] = hoge_sub(temp, work[11]);
      work[11] = hoge_lshift(work[11], 48);
      temp = work[8];
      work[8] = hoge_add(work[8], work[9]);
      work[9] = hoge_sub(temp, work[9]);
      temp = work[10];
      work[10] = hoge_add(work[10], work[11]);
      work[11] = hoge_sub(temp, work[11]);
      temp = work[12];
      work[12] = hoge_add(work[12], work[14]);
      work[14] = hoge_sub(temp, work[14]);
      temp = work[13];
      work[13] = hoge_add(work[13], work[15]);
      work[15] = hoge_sub(temp, work[15]);
      work[15] = hoge_lshift(work[15], 48);
      temp = work[12];
      work[12] = hoge_add(work[12], work[13]);
      work[13] = hoge_sub(temp, work[13]);
      temp = work[14];
      work[14] = hoge_add(work[14], work[15]);
      work[15] = hoge_sub(temp, work[15]);
      temp = work[16];
      work[16] = hoge_add(work[16], work[24]);
      work[24] = hoge_sub(temp, work[24]);
      temp = work[17];
      work[17] = hoge_add(work[17], work[25]);
      work[25] = hoge_sub(temp, work[25]);
      temp = work[18];
      work[18] = hoge_add(work[18], work[26]);
      work[26] = hoge_sub(temp, work[26]);
      temp = work[19];
      work[19] = hoge_add(work[19], work[27]);
      work[27] = hoge_sub(temp, work[27]);
      temp = work[20];
      work[20] = hoge_add(work[20], work[28]);
      work[28] = hoge_sub(temp, work[28]);
      temp = work[21];
      work[21] = hoge_add(work[21], work[29]);
      work[29] = hoge_sub(temp, work[29]);
      temp = work[22];
      work[22] = hoge_add(work[22], work[30]);
      work[30] = hoge_sub(temp, work[30]);
      temp = work[23];
      work[23] = hoge_add(work[23], work[31]);
      work[31] = hoge_sub(temp, work[31]);
      work[25] = hoge_lshift(work[25], 12);
      work[26] = hoge_lshift(work[26], 24);
      work[27] = hoge_lshift(work[27], 36);
      work[28] = hoge_lshift(work[28], 48);
      work[29] = hoge_lshift(work[29], 60);
      work[30] = hoge_lshift(work[30], 72);
      work[31] = hoge_lshift(work[31], 84);
      temp = work[16];
      work[16] = hoge_add(work[16], work[20]);
      work[20] = hoge_sub(temp, work[20]);
      temp = work[17];
      work[17] = hoge_add(work[17], work[21]);
      work[21] = hoge_sub(temp, work[21]);
      temp = work[18];
      work[18] = hoge_add(work[18], work[22]);
      work[22] = hoge_sub(temp, work[22]);
      temp = work[19];
      work[19] = hoge_add(work[19], work[23]);
      work[23] = hoge_sub(temp, work[23]);
      work[21] = hoge_lshift(work[21], 24);
      work[22] = hoge_lshift(work[22], 48);
      work[23] = hoge_lshift(work[23], 72);
      temp = work[16];
      work[16] = hoge_add(work[16], work[18]);
      work[18] = hoge_sub(temp, work[18]);
      temp = work[17];
      work[17] = hoge_add(work[17], work[19]);
      work[19] = hoge_sub(temp, work[19]);
      work[19] = hoge_lshift(work[19], 48);
      temp = work[16];
      work[16] = hoge_add(work[16], work[17]);
      work[17] = hoge_sub(temp, work[17]);
      temp = work[18];
      work[18] = hoge_add(work[18], work[19]);
      work[19] = hoge_sub(temp, work[19]);
      temp = work[20];
      work[20] = hoge_add(work[20], work[22]);
      work[22] = hoge_sub(temp, work[22]);
      temp = work[21];
      work[21] = hoge_add(work[21], work[23]);
      work[23] = hoge_sub(temp, work[23]);
      work[23] = hoge_lshift(work[23], 48);
      temp = work[20];
      work[20] = hoge_add(work[20], work[21]);
      work[21] = hoge_sub(temp, work[21]);
      temp = work[22];
      work[22] = hoge_add(work[22], work[23]);
      work[23] = hoge_sub(temp, work[23]);
      temp = work[24];
      work[24] = hoge_add(work[24], work[28]);
      work[28] = hoge_sub(temp, work[28]);
      temp = work[25];
      work[25] = hoge_add(work[25], work[29]);
      work[29] = hoge_sub(temp, work[29]);
      temp = work[26];
      work[26] = hoge_add(work[26], work[30]);
      work[30] = hoge_sub(temp, work[30]);
      temp = work[27];
      work[27] = hoge_add(work[27], work[31]);
      work[31] = hoge_sub(temp, work[31]);
      work[29] = hoge_lshift(work[29], 24);
      work[30] = hoge_lshift(work[30], 48);
      work[31] = hoge_lshift(work[31], 72);
      temp = work[24];
      work[24] = hoge_add(work[24], work[26]);
      work[26] = hoge_sub(temp, work[26]);
      temp = work[25];
      work[25] = hoge_add(work[25], work[27]);
      work[27] = hoge_sub(temp, work[27]);
      work[27] = hoge_lshift(work[27], 48);
      temp = work[24];
      work[24] = hoge_add(work[24], work[25]);
      work[25] = hoge_sub(temp, work[25]);
      temp = work[26];
      work[26] = hoge_add(work[26], work[27]);
      work[27] = hoge_sub(temp, work[27]);
      temp = work[28];
      work[28] = hoge_add(work[28], work[30]);
      work[30] = hoge_sub(temp, work[30]);
      temp = work[29];
      work[29] = hoge_add(work[29], work[31]);
      work[31] = hoge_sub(temp, work[31]);
      work[31] = hoge_lshift(work[31], 48);
      temp = work[28];
      work[28] = hoge_add(work[28], work[29]);
      work[29] = hoge_sub(temp, work[29]);
      temp = work[30];
      work[30] = hoge_add(work[30], work[31]);
      work[31] = hoge_sub(temp, work[31]);
    for (i = 0; i < 32; i = i + 1) intt_out_buf[i] <= work[i];
  end
endtask

task automatic compute_ntt;
  begin
    for (i = 0; i < 32; i = i + 1) work[i] = ntt_in_buf[i];
      temp = work[30];
      work[30] = hoge_add(work[30], work[31]);
      work[31] = hoge_sub(temp, work[31]);
      temp = work[28];
      work[28] = hoge_add(work[28], work[29]);
      work[29] = hoge_sub(temp, work[29]);
      work[31] = hoge_lshift(work[31], 144);
      temp = work[28];
      work[28] = hoge_add(work[28], work[30]);
      work[30] = hoge_sub(temp, work[30]);
      temp = work[29];
      work[29] = hoge_add(work[29], work[31]);
      work[31] = hoge_sub(temp, work[31]);
      temp = work[26];
      work[26] = hoge_add(work[26], work[27]);
      work[27] = hoge_sub(temp, work[27]);
      temp = work[24];
      work[24] = hoge_add(work[24], work[25]);
      work[25] = hoge_sub(temp, work[25]);
      work[27] = hoge_lshift(work[27], 144);
      temp = work[24];
      work[24] = hoge_add(work[24], work[26]);
      work[26] = hoge_sub(temp, work[26]);
      temp = work[25];
      work[25] = hoge_add(work[25], work[27]);
      work[27] = hoge_sub(temp, work[27]);
      work[29] = hoge_lshift(work[29], 168);
      work[30] = hoge_lshift(work[30], 144);
      work[31] = hoge_lshift(work[31], 120);
      temp = work[24];
      work[24] = hoge_add(work[24], work[28]);
      work[28] = hoge_sub(temp, work[28]);
      temp = work[25];
      work[25] = hoge_add(work[25], work[29]);
      work[29] = hoge_sub(temp, work[29]);
      temp = work[26];
      work[26] = hoge_add(work[26], work[30]);
      work[30] = hoge_sub(temp, work[30]);
      temp = work[27];
      work[27] = hoge_add(work[27], work[31]);
      work[31] = hoge_sub(temp, work[31]);
      temp = work[22];
      work[22] = hoge_add(work[22], work[23]);
      work[23] = hoge_sub(temp, work[23]);
      temp = work[20];
      work[20] = hoge_add(work[20], work[21]);
      work[21] = hoge_sub(temp, work[21]);
      work[23] = hoge_lshift(work[23], 144);
      temp = work[20];
      work[20] = hoge_add(work[20], work[22]);
      work[22] = hoge_sub(temp, work[22]);
      temp = work[21];
      work[21] = hoge_add(work[21], work[23]);
      work[23] = hoge_sub(temp, work[23]);
      temp = work[18];
      work[18] = hoge_add(work[18], work[19]);
      work[19] = hoge_sub(temp, work[19]);
      temp = work[16];
      work[16] = hoge_add(work[16], work[17]);
      work[17] = hoge_sub(temp, work[17]);
      work[19] = hoge_lshift(work[19], 144);
      temp = work[16];
      work[16] = hoge_add(work[16], work[18]);
      work[18] = hoge_sub(temp, work[18]);
      temp = work[17];
      work[17] = hoge_add(work[17], work[19]);
      work[19] = hoge_sub(temp, work[19]);
      work[21] = hoge_lshift(work[21], 168);
      work[22] = hoge_lshift(work[22], 144);
      work[23] = hoge_lshift(work[23], 120);
      temp = work[16];
      work[16] = hoge_add(work[16], work[20]);
      work[20] = hoge_sub(temp, work[20]);
      temp = work[17];
      work[17] = hoge_add(work[17], work[21]);
      work[21] = hoge_sub(temp, work[21]);
      temp = work[18];
      work[18] = hoge_add(work[18], work[22]);
      work[22] = hoge_sub(temp, work[22]);
      temp = work[19];
      work[19] = hoge_add(work[19], work[23]);
      work[23] = hoge_sub(temp, work[23]);
      work[25] = hoge_lshift(work[25], 180);
      work[26] = hoge_lshift(work[26], 168);
      work[27] = hoge_lshift(work[27], 156);
      work[28] = hoge_lshift(work[28], 144);
      work[29] = hoge_lshift(work[29], 132);
      work[30] = hoge_lshift(work[30], 120);
      work[31] = hoge_lshift(work[31], 108);
      temp = work[16];
      work[16] = hoge_add(work[16], work[24]);
      work[24] = hoge_sub(temp, work[24]);
      temp = work[17];
      work[17] = hoge_add(work[17], work[25]);
      work[25] = hoge_sub(temp, work[25]);
      temp = work[18];
      work[18] = hoge_add(work[18], work[26]);
      work[26] = hoge_sub(temp, work[26]);
      temp = work[19];
      work[19] = hoge_add(work[19], work[27]);
      work[27] = hoge_sub(temp, work[27]);
      temp = work[20];
      work[20] = hoge_add(work[20], work[28]);
      work[28] = hoge_sub(temp, work[28]);
      temp = work[21];
      work[21] = hoge_add(work[21], work[29]);
      work[29] = hoge_sub(temp, work[29]);
      temp = work[22];
      work[22] = hoge_add(work[22], work[30]);
      work[30] = hoge_sub(temp, work[30]);
      temp = work[23];
      work[23] = hoge_add(work[23], work[31]);
      work[31] = hoge_sub(temp, work[31]);
      temp = work[14];
      work[14] = hoge_add(work[14], work[15]);
      work[15] = hoge_sub(temp, work[15]);
      temp = work[12];
      work[12] = hoge_add(work[12], work[13]);
      work[13] = hoge_sub(temp, work[13]);
      work[15] = hoge_lshift(work[15], 144);
      temp = work[12];
      work[12] = hoge_add(work[12], work[14]);
      work[14] = hoge_sub(temp, work[14]);
      temp = work[13];
      work[13] = hoge_add(work[13], work[15]);
      work[15] = hoge_sub(temp, work[15]);
      temp = work[10];
      work[10] = hoge_add(work[10], work[11]);
      work[11] = hoge_sub(temp, work[11]);
      temp = work[8];
      work[8] = hoge_add(work[8], work[9]);
      work[9] = hoge_sub(temp, work[9]);
      work[11] = hoge_lshift(work[11], 144);
      temp = work[8];
      work[8] = hoge_add(work[8], work[10]);
      work[10] = hoge_sub(temp, work[10]);
      temp = work[9];
      work[9] = hoge_add(work[9], work[11]);
      work[11] = hoge_sub(temp, work[11]);
      work[13] = hoge_lshift(work[13], 168);
      work[14] = hoge_lshift(work[14], 144);
      work[15] = hoge_lshift(work[15], 120);
      temp = work[8];
      work[8] = hoge_add(work[8], work[12]);
      work[12] = hoge_sub(temp, work[12]);
      temp = work[9];
      work[9] = hoge_add(work[9], work[13]);
      work[13] = hoge_sub(temp, work[13]);
      temp = work[10];
      work[10] = hoge_add(work[10], work[14]);
      work[14] = hoge_sub(temp, work[14]);
      temp = work[11];
      work[11] = hoge_add(work[11], work[15]);
      work[15] = hoge_sub(temp, work[15]);
      temp = work[6];
      work[6] = hoge_add(work[6], work[7]);
      work[7] = hoge_sub(temp, work[7]);
      temp = work[4];
      work[4] = hoge_add(work[4], work[5]);
      work[5] = hoge_sub(temp, work[5]);
      work[7] = hoge_lshift(work[7], 144);
      temp = work[4];
      work[4] = hoge_add(work[4], work[6]);
      work[6] = hoge_sub(temp, work[6]);
      temp = work[5];
      work[5] = hoge_add(work[5], work[7]);
      work[7] = hoge_sub(temp, work[7]);
      temp = work[2];
      work[2] = hoge_add(work[2], work[3]);
      work[3] = hoge_sub(temp, work[3]);
      temp = work[0];
      work[0] = hoge_add(work[0], work[1]);
      work[1] = hoge_sub(temp, work[1]);
      work[3] = hoge_lshift(work[3], 144);
      temp = work[0];
      work[0] = hoge_add(work[0], work[2]);
      work[2] = hoge_sub(temp, work[2]);
      temp = work[1];
      work[1] = hoge_add(work[1], work[3]);
      work[3] = hoge_sub(temp, work[3]);
      work[5] = hoge_lshift(work[5], 168);
      work[6] = hoge_lshift(work[6], 144);
      work[7] = hoge_lshift(work[7], 120);
      temp = work[0];
      work[0] = hoge_add(work[0], work[4]);
      work[4] = hoge_sub(temp, work[4]);
      temp = work[1];
      work[1] = hoge_add(work[1], work[5]);
      work[5] = hoge_sub(temp, work[5]);
      temp = work[2];
      work[2] = hoge_add(work[2], work[6]);
      work[6] = hoge_sub(temp, work[6]);
      temp = work[3];
      work[3] = hoge_add(work[3], work[7]);
      work[7] = hoge_sub(temp, work[7]);
      work[9] = hoge_lshift(work[9], 180);
      work[10] = hoge_lshift(work[10], 168);
      work[11] = hoge_lshift(work[11], 156);
      work[12] = hoge_lshift(work[12], 144);
      work[13] = hoge_lshift(work[13], 132);
      work[14] = hoge_lshift(work[14], 120);
      work[15] = hoge_lshift(work[15], 108);
      temp = work[0];
      work[0] = hoge_add(work[0], work[8]);
      work[8] = hoge_sub(temp, work[8]);
      temp = work[1];
      work[1] = hoge_add(work[1], work[9]);
      work[9] = hoge_sub(temp, work[9]);
      temp = work[2];
      work[2] = hoge_add(work[2], work[10]);
      work[10] = hoge_sub(temp, work[10]);
      temp = work[3];
      work[3] = hoge_add(work[3], work[11]);
      work[11] = hoge_sub(temp, work[11]);
      temp = work[4];
      work[4] = hoge_add(work[4], work[12]);
      work[12] = hoge_sub(temp, work[12]);
      temp = work[5];
      work[5] = hoge_add(work[5], work[13]);
      work[13] = hoge_sub(temp, work[13]);
      temp = work[6];
      work[6] = hoge_add(work[6], work[14]);
      work[14] = hoge_sub(temp, work[14]);
      temp = work[7];
      work[7] = hoge_add(work[7], work[15]);
      work[15] = hoge_sub(temp, work[15]);
      work[17] = hoge_lshift(work[17], 186);
      work[18] = hoge_lshift(work[18], 180);
      work[19] = hoge_lshift(work[19], 174);
      work[20] = hoge_lshift(work[20], 168);
      work[21] = hoge_lshift(work[21], 162);
      work[22] = hoge_lshift(work[22], 156);
      work[23] = hoge_lshift(work[23], 150);
      work[24] = hoge_lshift(work[24], 144);
      work[25] = hoge_lshift(work[25], 138);
      work[26] = hoge_lshift(work[26], 132);
      work[27] = hoge_lshift(work[27], 126);
      work[28] = hoge_lshift(work[28], 120);
      work[29] = hoge_lshift(work[29], 114);
      work[30] = hoge_lshift(work[30], 108);
      work[31] = hoge_lshift(work[31], 102);
      temp = work[0];
      work[0] = hoge_add(work[0], work[16]);
      work[16] = hoge_sub(temp, work[16]);
      temp = work[1];
      work[1] = hoge_add(work[1], work[17]);
      work[17] = hoge_sub(temp, work[17]);
      temp = work[2];
      work[2] = hoge_add(work[2], work[18]);
      work[18] = hoge_sub(temp, work[18]);
      temp = work[3];
      work[3] = hoge_add(work[3], work[19]);
      work[19] = hoge_sub(temp, work[19]);
      temp = work[4];
      work[4] = hoge_add(work[4], work[20]);
      work[20] = hoge_sub(temp, work[20]);
      temp = work[5];
      work[5] = hoge_add(work[5], work[21]);
      work[21] = hoge_sub(temp, work[21]);
      temp = work[6];
      work[6] = hoge_add(work[6], work[22]);
      work[22] = hoge_sub(temp, work[22]);
      temp = work[7];
      work[7] = hoge_add(work[7], work[23]);
      work[23] = hoge_sub(temp, work[23]);
      temp = work[8];
      work[8] = hoge_add(work[8], work[24]);
      work[24] = hoge_sub(temp, work[24]);
      temp = work[9];
      work[9] = hoge_add(work[9], work[25]);
      work[25] = hoge_sub(temp, work[25]);
      temp = work[10];
      work[10] = hoge_add(work[10], work[26]);
      work[26] = hoge_sub(temp, work[26]);
      temp = work[11];
      work[11] = hoge_add(work[11], work[27]);
      work[27] = hoge_sub(temp, work[27]);
      temp = work[12];
      work[12] = hoge_add(work[12], work[28]);
      work[28] = hoge_sub(temp, work[28]);
      temp = work[13];
      work[13] = hoge_add(work[13], work[29]);
      work[29] = hoge_sub(temp, work[29]);
      temp = work[14];
      work[14] = hoge_add(work[14], work[30]);
      work[30] = hoge_sub(temp, work[30]);
      temp = work[15];
      work[15] = hoge_add(work[15], work[31]);
      work[31] = hoge_sub(temp, work[31]);
    for (i = 0; i < 32; i = i + 1) ntt_out_buf[i] <= work[i];
  end
endtask

always @(posedge clock) begin
  if (reset) begin
    io_intt_validout <= 1'b0;
    io_ntt_validout <= 1'b0;
    intt_pending <= 1'b0;
    ntt_pending <= 1'b0;
    for (i = 0; i < 32; i = i + 1) begin
      intt_in_buf[i] <= 64'd0;
      intt_out_buf[i] <= 64'd0;
      ntt_in_buf[i] <= 64'd0;
      ntt_out_buf[i] <= 64'd0;
    end
  end else begin
    io_intt_validout <= intt_pending;
    io_ntt_validout <= ntt_pending;
      io_intt_out_0 <= intt_out_buf[0];
      io_intt_out_1 <= intt_out_buf[1];
      io_intt_out_2 <= intt_out_buf[2];
      io_intt_out_3 <= intt_out_buf[3];
      io_intt_out_4 <= intt_out_buf[4];
      io_intt_out_5 <= intt_out_buf[5];
      io_intt_out_6 <= intt_out_buf[6];
      io_intt_out_7 <= intt_out_buf[7];
      io_intt_out_8 <= intt_out_buf[8];
      io_intt_out_9 <= intt_out_buf[9];
      io_intt_out_10 <= intt_out_buf[10];
      io_intt_out_11 <= intt_out_buf[11];
      io_intt_out_12 <= intt_out_buf[12];
      io_intt_out_13 <= intt_out_buf[13];
      io_intt_out_14 <= intt_out_buf[14];
      io_intt_out_15 <= intt_out_buf[15];
      io_intt_out_16 <= intt_out_buf[16];
      io_intt_out_17 <= intt_out_buf[17];
      io_intt_out_18 <= intt_out_buf[18];
      io_intt_out_19 <= intt_out_buf[19];
      io_intt_out_20 <= intt_out_buf[20];
      io_intt_out_21 <= intt_out_buf[21];
      io_intt_out_22 <= intt_out_buf[22];
      io_intt_out_23 <= intt_out_buf[23];
      io_intt_out_24 <= intt_out_buf[24];
      io_intt_out_25 <= intt_out_buf[25];
      io_intt_out_26 <= intt_out_buf[26];
      io_intt_out_27 <= intt_out_buf[27];
      io_intt_out_28 <= intt_out_buf[28];
      io_intt_out_29 <= intt_out_buf[29];
      io_intt_out_30 <= intt_out_buf[30];
      io_intt_out_31 <= intt_out_buf[31];
      io_ntt_out_0 <= ntt_out_buf[0];
      io_ntt_out_1 <= ntt_out_buf[1];
      io_ntt_out_2 <= ntt_out_buf[2];
      io_ntt_out_3 <= ntt_out_buf[3];
      io_ntt_out_4 <= ntt_out_buf[4];
      io_ntt_out_5 <= ntt_out_buf[5];
      io_ntt_out_6 <= ntt_out_buf[6];
      io_ntt_out_7 <= ntt_out_buf[7];
      io_ntt_out_8 <= ntt_out_buf[8];
      io_ntt_out_9 <= ntt_out_buf[9];
      io_ntt_out_10 <= ntt_out_buf[10];
      io_ntt_out_11 <= ntt_out_buf[11];
      io_ntt_out_12 <= ntt_out_buf[12];
      io_ntt_out_13 <= ntt_out_buf[13];
      io_ntt_out_14 <= ntt_out_buf[14];
      io_ntt_out_15 <= ntt_out_buf[15];
      io_ntt_out_16 <= ntt_out_buf[16];
      io_ntt_out_17 <= ntt_out_buf[17];
      io_ntt_out_18 <= ntt_out_buf[18];
      io_ntt_out_19 <= ntt_out_buf[19];
      io_ntt_out_20 <= ntt_out_buf[20];
      io_ntt_out_21 <= ntt_out_buf[21];
      io_ntt_out_22 <= ntt_out_buf[22];
      io_ntt_out_23 <= ntt_out_buf[23];
      io_ntt_out_24 <= ntt_out_buf[24];
      io_ntt_out_25 <= ntt_out_buf[25];
      io_ntt_out_26 <= ntt_out_buf[26];
      io_ntt_out_27 <= ntt_out_buf[27];
      io_ntt_out_28 <= ntt_out_buf[28];
      io_ntt_out_29 <= ntt_out_buf[29];
      io_ntt_out_30 <= ntt_out_buf[30];
      io_ntt_out_31 <= ntt_out_buf[31];

intt_pending <= io_intt_validin;
ntt_pending <= io_ntt_validin;

if (io_intt_validin) begin
        intt_in_buf[0] = io_intt_in_0;
        intt_in_buf[1] = io_intt_in_1;
        intt_in_buf[2] = io_intt_in_2;
        intt_in_buf[3] = io_intt_in_3;
        intt_in_buf[4] = io_intt_in_4;
        intt_in_buf[5] = io_intt_in_5;
        intt_in_buf[6] = io_intt_in_6;
        intt_in_buf[7] = io_intt_in_7;
        intt_in_buf[8] = io_intt_in_8;
        intt_in_buf[9] = io_intt_in_9;
        intt_in_buf[10] = io_intt_in_10;
        intt_in_buf[11] = io_intt_in_11;
        intt_in_buf[12] = io_intt_in_12;
        intt_in_buf[13] = io_intt_in_13;
        intt_in_buf[14] = io_intt_in_14;
        intt_in_buf[15] = io_intt_in_15;
        intt_in_buf[16] = io_intt_in_16;
        intt_in_buf[17] = io_intt_in_17;
        intt_in_buf[18] = io_intt_in_18;
        intt_in_buf[19] = io_intt_in_19;
        intt_in_buf[20] = io_intt_in_20;
        intt_in_buf[21] = io_intt_in_21;
        intt_in_buf[22] = io_intt_in_22;
        intt_in_buf[23] = io_intt_in_23;
        intt_in_buf[24] = io_intt_in_24;
        intt_in_buf[25] = io_intt_in_25;
        intt_in_buf[26] = io_intt_in_26;
        intt_in_buf[27] = io_intt_in_27;
        intt_in_buf[28] = io_intt_in_28;
        intt_in_buf[29] = io_intt_in_29;
        intt_in_buf[30] = io_intt_in_30;
        intt_in_buf[31] = io_intt_in_31;
  compute_intt();
end

if (io_ntt_validin) begin
        ntt_in_buf[0] = io_ntt_in_0;
        ntt_in_buf[1] = io_ntt_in_1;
        ntt_in_buf[2] = io_ntt_in_2;
        ntt_in_buf[3] = io_ntt_in_3;
        ntt_in_buf[4] = io_ntt_in_4;
        ntt_in_buf[5] = io_ntt_in_5;
        ntt_in_buf[6] = io_ntt_in_6;
        ntt_in_buf[7] = io_ntt_in_7;
        ntt_in_buf[8] = io_ntt_in_8;
        ntt_in_buf[9] = io_ntt_in_9;
        ntt_in_buf[10] = io_ntt_in_10;
        ntt_in_buf[11] = io_ntt_in_11;
        ntt_in_buf[12] = io_ntt_in_12;
        ntt_in_buf[13] = io_ntt_in_13;
        ntt_in_buf[14] = io_ntt_in_14;
        ntt_in_buf[15] = io_ntt_in_15;
        ntt_in_buf[16] = io_ntt_in_16;
        ntt_in_buf[17] = io_ntt_in_17;
        ntt_in_buf[18] = io_ntt_in_18;
        ntt_in_buf[19] = io_ntt_in_19;
        ntt_in_buf[20] = io_ntt_in_20;
        ntt_in_buf[21] = io_ntt_in_21;
        ntt_in_buf[22] = io_ntt_in_22;
        ntt_in_buf[23] = io_ntt_in_23;
        ntt_in_buf[24] = io_ntt_in_24;
        ntt_in_buf[25] = io_ntt_in_25;
        ntt_in_buf[26] = io_ntt_in_26;
        ntt_in_buf[27] = io_ntt_in_27;
        ntt_in_buf[28] = io_ntt_in_28;
        ntt_in_buf[29] = io_ntt_in_29;
        ntt_in_buf[30] = io_ntt_in_30;
        ntt_in_buf[31] = io_ntt_in_31;
        compute_ntt();
      end
    end
  end
endmodule
