#!/usr/bin/env python3
"""Generate fixed-size RTL references for the small NTT tasks."""

from __future__ import annotations

import importlib.util
import textwrap
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = REPO_ROOT / "variants" / "small-ntt" / "rtl"


def load_small_hls() -> Any:
    path = REPO_ROOT / "scripts" / "run_small_variant_hls_synth_compare.py"
    spec = importlib.util.spec_from_file_location("small_hls", path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


SMALL = load_small_hls()


def banner(note: str | None = None) -> str:
    lines = [
        "// Generated by scripts/generate_small_ntt_rtl.py.\n",
        "// Fixed-size synthesizable RTL reference for small NTT metric tasks.\n",
    ]
    if note:
        lines.insert(2, f"// {note}\n")
    lines.append("\n")
    return "".join(lines)


def lane_ports(prefix: str, direction: str, width: int, lanes: int, comma: bool = True) -> list[str]:
    suffix = "," if comma else ""
    return [f"  {direction} [{width - 1}:0] {prefix}_{lane}{suffix}" for lane in range(lanes)]


def hoge_add(a: int, b: int) -> int:
    return (a + b) % SMALL.HOGE_P


def hoge_sub(a: int, b: int) -> int:
    return (a - b) % SMALL.HOGE_P


def hoge_lshift(value: int, shift: int) -> int:
    return (value * pow(2, shift, SMALL.HOGE_P)) % SMALL.HOGE_P


def hoge_butterfly(work: list[int], offset: int, size: int) -> None:
    for index in range(size // 2):
        temp = work[offset + index]
        work[offset + index] = hoge_add(work[offset + index], work[offset + index + size // 2])
        work[offset + index + size // 2] = hoge_sub(temp, work[offset + index + size // 2])


def hoge_intt_butterfly(work: list[int], offset: int, size: int, radixbit: int) -> None:
    if radixbit == 0:
        return
    hoge_butterfly(work, offset, size)
    block = size >> radixbit
    for i in range(1, 1 << (radixbit - 1)):
        shift = 3 * (i << (6 - radixbit))
        for j in range(block):
            idx = offset + i * block + j + size // 2
            work[idx] = hoge_lshift(work[idx], shift)
    hoge_intt_butterfly(work, offset, size // 2, radixbit - 1)
    hoge_intt_butterfly(work, offset + size // 2, size // 2, radixbit - 1)


def hoge_ntt_butterfly(work: list[int], offset: int, size: int, radixbit: int) -> None:
    if radixbit == 0:
        return
    hoge_ntt_butterfly(work, offset + size // 2, size // 2, radixbit - 1)
    hoge_ntt_butterfly(work, offset, size // 2, radixbit - 1)
    block = size >> radixbit
    if radixbit != 1:
        for i in range(1, 1 << (radixbit - 1)):
            shift = 3 * (64 - (i << (6 - radixbit)))
            for j in range(block):
                idx = offset + i * block + j + size // 2
                work[idx] = hoge_lshift(work[idx], shift)
    hoge_butterfly(work, offset, size)


def hoge_intt_matrix(nbit: int) -> list[list[int]]:
    n = 1 << nbit
    tables = SMALL.generate_hoge_tables(nbit)
    matrix: list[list[int]] = []
    for column in range(n):
        work = [0] * n
        work[column] = tables["HOGE_INTT_TWIST"][column]
        hoge_intt_butterfly(work, 0, n, nbit)
        matrix.append(work)
    return matrix


def hoge_ntt_matrix(nbit: int) -> list[list[int]]:
    n = 1 << nbit
    tables = SMALL.generate_hoge_tables(nbit)
    matrix: list[list[int]] = []
    for column in range(n):
        work = [0] * n
        work[column] = 1
        hoge_ntt_butterfly(work, 0, n, nbit)
        out = [
            SMALL.hoge_mul_mod(SMALL.hoge_mul_mod(work[i], tables["HOGE_NTT_TWIST"][i]), tables["HOGE_INVN"][0])
            for i in range(n)
        ]
        matrix.append(out)
    return matrix


def emit_hoge_transform(kind: str, matrix: list[list[int]], in_width: int, out_width: int) -> str:
    n = len(matrix)
    lines: list[str] = []
    for row in range(n):
        lines.append("      acc = 64'd0;")
        for col in range(n):
            const = matrix[col][row]
            if const:
                operand = f"{{32'd0, {kind}_in_buf[{col}]}}" if in_width == 32 else f"{kind}_in_buf[{col}]"
                lines.append(f"      acc = hoge_add(acc, hoge_mul({operand}, 64'd{const}));")
        mask = "" if out_width == 64 else "[31:0]"
        lines.append(f"      {kind}_out_buf[{row}] <= acc{mask};")
    return "\n".join(lines)


def generate_hoge32() -> str:
    n = 32
    intt_matrix = hoge_intt_matrix(5)
    ntt_matrix = hoge_ntt_matrix(5)
    return banner("HOGE p64 arithmetic uses reduction for p = 2^64 - 2^32 + 1.") + textwrap.dedent(
        f"""\
        module SmallHoge32P64Rtl(
          input clock,
          input reset,
          input io_intt_validin,
        """
    ) + "\n".join(lane_ports("io_intt_in", "input", 32, n)) + "\n" + "\n".join(
        lane_ports("io_intt_out", "output reg", 64, n)
    ) + "\n" + textwrap.dedent(
        """\
          output reg io_intt_validout,
          input io_ntt_validin,
        """
    ) + "\n".join(lane_ports("io_ntt_in", "input", 64, n)) + "\n" + "\n".join(
        lane_ports("io_ntt_out", "output reg", 32, n)
    ) + "\n" + textwrap.dedent(
        """\
          output reg io_ntt_validout
        );
          localparam [63:0] HOGE_P = 64'hffffffff00000001;

          reg [31:0] intt_in_buf [0:31];
          reg [63:0] intt_out_buf [0:31];
          reg [63:0] ntt_in_buf [0:31];
          reg [31:0] ntt_out_buf [0:31];
          reg intt_pending;
          reg ntt_pending;
          reg [63:0] acc;
          integer i;

          function automatic [63:0] hoge_normalize(input [63:0] value);
            begin
              hoge_normalize = (value >= HOGE_P) ? value + 64'h00000000ffffffff : value;
            end
          endfunction

          function automatic [63:0] hoge_add(input [63:0] left, input [63:0] right);
            reg [64:0] sum;
            begin
              sum = {1'b0, left} + {1'b0, right};
              hoge_add = (sum[64] || sum[63:0] >= HOGE_P) ? sum[63:0] + 64'h00000000ffffffff : sum[63:0];
            end
          endfunction

          function automatic [63:0] hoge_mul(input [63:0] left, input [63:0] right);
            reg [127:0] product;
            reg [63:0] lo;
            reg [31:0] w0;
            reg [31:0] w1;
            reg [31:0] w2;
            reg [31:0] w3;
            reg [63:0] res;
            begin
              product = left * right;
              lo = product[63:0];
              w0 = product[31:0];
              w1 = product[63:32];
              w2 = product[95:64];
              w3 = product[127:96];
              res = (({32'd0, w1} + {32'd0, w2}) << 32) + {32'd0, w0} - {32'd0, w3} - {32'd0, w2};
              if ((res > lo) && (w2 == 0)) res = res - 64'h00000000ffffffff;
              if ((res < lo) && (w2 != 0)) res = res + 64'h00000000ffffffff;
              hoge_mul = hoge_normalize(res);
            end
          endfunction

          always @(posedge clock) begin
            if (reset) begin
              io_intt_validout <= 1'b0;
              io_ntt_validout <= 1'b0;
              intt_pending <= 1'b0;
              ntt_pending <= 1'b0;
              for (i = 0; i < 32; i = i + 1) begin
                intt_in_buf[i] <= 32'd0;
                intt_out_buf[i] <= 64'd0;
                ntt_in_buf[i] <= 64'd0;
                ntt_out_buf[i] <= 32'd0;
              end
            end else begin
              io_intt_validout <= intt_pending;
              io_ntt_validout <= ntt_pending;
        """
    ) + "\n".join(
        f"      io_intt_out_{i} <= intt_out_buf[{i}];" for i in range(n)
    ) + "\n" + "\n".join(
        f"      io_ntt_out_{i} <= ntt_out_buf[{i}];" for i in range(n)
    ) + textwrap.dedent(
        """

              intt_pending <= io_intt_validin;
              ntt_pending <= io_ntt_validin;

              if (io_intt_validin) begin
        """
    ) + "\n".join(f"        intt_in_buf[{i}] = io_intt_in_{i};" for i in range(n)) + "\n" + emit_hoge_transform(
        "intt", intt_matrix, 32, 64
    ) + textwrap.dedent(
        """
              end

              if (io_ntt_validin) begin
        """
    ) + "\n".join(f"        ntt_in_buf[{i}] = io_ntt_in_{i};" for i in range(n)) + "\n" + emit_hoge_transform(
        "ntt", ntt_matrix, 64, 32
    ) + textwrap.dedent(
        """
              end
            end
          end
        endmodule
        """
    )


def y_br3(x: int) -> int:
    return ((x & 1) << 2) | (x & 2) | ((x & 4) >> 2)


def y_se27(value: int) -> int:
    value &= (1 << SMALL.YATA_WORDBITS) - 1
    if value & (1 << (SMALL.YATA_WORDBITS - 1)):
        value -= 1 << SMALL.YATA_WORDBITS
    return value


def y_add_model(a: int, b: int) -> int:
    result = a + b
    if result >= SMALL.YATA_P:
        return result - SMALL.YATA_P
    if result <= -SMALL.YATA_P:
        return result + SMALL.YATA_P
    return result


def y_sub_model(a: int, b: int) -> int:
    result = a - b
    if result >= SMALL.YATA_P:
        return result - SMALL.YATA_P
    if result <= -SMALL.YATA_P:
        return result + SMALL.YATA_P
    return result


def y_sredc_model(a: int) -> int:
    mask = (1 << SMALL.YATA_WORDBITS) - 1
    a0 = a & mask
    a1 = a >> SMALL.YATA_WORDBITS
    m = y_se27(-((a0 * SMALL.YATA_K) << SMALL.YATA_SHIFTAMOUNT) + a0)
    t1 = (((m * SMALL.YATA_K) << SMALL.YATA_SHIFTAMOUNT) + m) >> SMALL.YATA_WORDBITS
    return y_se27(a1 - t1)


def y_mul_model(a: int, b: int) -> int:
    return y_sredc_model(a * b)


def y_const_model(a: int, radixbit: int, num: int) -> int:
    factor = 1
    for _ in range(num * (4 >> (radixbit - 1))):
        factor *= 5
    return (a * factor) << (num * (16 >> (radixbit - 1)))


def y_both_mod_model(res: list[int], off: int, size: int) -> None:
    for idx in range(size // 2):
        temp = res[off + idx]
        res[off + idx] = y_add_model(res[off + idx], res[off + idx + size // 2])
        res[off + idx + size // 2] = y_sub_model(temp, res[off + idx + size // 2])


def y_add_add_model(res: list[int], off: int, size: int) -> None:
    for idx in range(size // 2):
        temp = res[off + idx]
        res[off + idx] = y_add_model(res[off + idx], res[off + idx + size // 2])
        res[off + idx + size // 2] = temp - res[off + idx + size // 2]


def y_both_sredc_model(res: list[int], off: int, size: int) -> None:
    for idx in range(size // 2):
        temp = res[off + idx]
        res[off + idx] = y_sredc_model(res[off + idx] + res[off + idx + size // 2])
        res[off + idx + size // 2] = y_sredc_model(temp - res[off + idx + size // 2])


def y_intt_r2_model(res: list[int], off: int, size: int) -> None:
    y_add_add_model(res, off, size)
    y_both_mod_model(res, off, size // 2)
    block = size >> 2
    for j in range(block):
        idx = off + j + size // 2 + block
        res[idx] = y_const_model(res[idx], 2, 1)
    y_both_sredc_model(res, off + size // 2, size // 2)


def y_intt_r3_model(res: list[int], off: int, size: int) -> None:
    y_add_add_model(res, off, size)
    y_intt_r2_model(res, off, size // 2)
    block = size >> 3
    for i in range(block):
        idx = off + 2 * block + i + size // 2
        res[idx] = y_const_model(res[idx], 3, 2)
        temp = res[off + i + size // 2]
        res[off + i + size // 2] += res[idx]
        res[idx] = temp - res[idx]
    for i in range(block):
        a = off + block + i + size // 2
        b = off + 3 * block + i + size // 2
        temp = y_const_model(res[a], 3, 3)
        res[a] = y_const_model(res[a], 3, 1) + y_const_model(res[b], 3, 3)
        res[b] = temp + y_const_model(res[b], 3, 1)
    y_both_sredc_model(res, off + size // 2, size // 4)
    y_both_sredc_model(res, off + 3 * size // 4, size // 4)


def y_intt_model(values: list[int], nbit: int) -> list[int]:
    tables = SMALL.generate_yata_tables(nbit)
    res = [y_mul_model(values[i], tables["YATA_INTT_TWIST"][i]) for i in range(1 << nbit)]
    for sizebit in range(nbit, 3, -3):
        size = 1 << sizebit
        num_block = 1 << (nbit - sizebit)
        for block in range(num_block):
            off = size * block
            y_intt_r3_model(res, off, size)
            subblock = size >> 3
            for i in range(1, 8):
                stride = y_br3(i) * num_block
                table = "YATA_INTT_TABLE1" if i > 1 else "YATA_INTT_TABLE0"
                for idx in range(subblock):
                    pos = off + i * subblock + idx
                    res[pos] = y_mul_model(res[pos], tables[table][stride * idx])
    for block in range(1 << (nbit - 3)):
        y_intt_r3_model(res, 8 * block, 8)
    return res


def y_ntt_r2_model(res: list[int], off: int, size: int, redc: bool) -> None:
    y_both_mod_model(res, off, size // 2)
    y_both_mod_model(res, off + size // 2, size // 2)
    for idx in range(size // 4):
        a = off + idx
        b = off + idx + size // 2
        temp = res[a]
        res[a] = y_add_model(res[a], res[b])
        res[b] = y_sub_model(temp, res[b])
    for idx in range(size // 4, size // 2):
        a = off + idx
        b = off + idx + size // 2
        temp = res[a]
        res[b] = -y_const_model(res[b], 2, 1)
        if redc:
            res[a] = y_sredc_model(res[a] + res[b])
            res[b] = y_sredc_model(temp - res[b])
        else:
            res[a] = res[a] + res[b]
            res[b] = temp - res[b]


def y_ntt_r3_model(res: list[int], off: int, size: int) -> None:
    y_ntt_r2_model(res, off, size // 2, False)
    y_both_mod_model(res, off + 2 * size // 4, size // 4)
    y_both_mod_model(res, off + 3 * size // 4, size // 4)
    block = size >> 3
    for idx in range(size // 2, size // 2 + block):
        temp = res[off + idx]
        res[off + idx] = y_add_model(res[off + idx], res[off + idx + size // 4])
        res[off + idx + size // 4] = -y_const_model(temp - res[off + idx + size // 4], 3, 2)
    for idx in range(size // 2 + block, size // 2 + 2 * block):
        temp = -y_const_model(res[off + idx], 3, 1)
        res[off + idx] = -y_const_model(res[off + idx], 3, 3) - y_const_model(res[off + idx + size // 4], 3, 1)
        res[off + idx + size // 4] = temp - y_const_model(res[off + idx + size // 4], 3, 3)
    for idx in range(block):
        a = off + idx
        b = off + idx + size // 2
        temp = res[a]
        res[a] = y_add_model(res[a], res[b])
        res[b] = y_sub_model(temp, res[b])
    for i in range(1, 4):
        for idx in range(i * block, (i + 1) * block):
            a = off + idx
            b = off + idx + size // 2
            temp = res[a]
            res[a] = y_sredc_model(res[a] + res[b])
            res[b] = y_sredc_model(temp - res[b])


def y_ntt_residue_model(values: list[int], nbit: int) -> list[int]:
    tables = SMALL.generate_yata_tables(nbit)
    res = list(values)
    for block in range(1 << (nbit - 3)):
        y_ntt_r3_model(res, 8 * block, 8)
    for sizebit in range(6, nbit + 1, 3):
        size = 1 << sizebit
        num_block = 1 << (nbit - sizebit)
        block_size = size >> 3
        for block in range(num_block):
            off = size * block
            for i in range(8):
                stride = y_br3(i) * num_block
                suboff = off + i * block_size
                for idx in range(block_size):
                    table_is_1 = ((idx >> (sizebit - 6)) & 3) != 0
                    pos = suboff + idx
                    if stride == 0:
                        if table_is_1:
                            res[pos] = y_mul_model(res[pos], SMALL.YATA_R2)
                    else:
                        table = "YATA_NTT_TABLE1" if table_is_1 else "YATA_NTT_TABLE0"
                        res[pos] = y_mul_model(res[pos], tables[table][stride * idx])
            y_ntt_r3_model(res, off, size)
    return [y_mul_model(res[i], tables["YATA_NTT_TWIST"][i]) for i in range(1 << nbit)]


def y_emit_both_mod(work: str, off: int, size: int) -> list[str]:
    lines = []
    for idx in range(size // 2):
        a = off + idx
        b = off + idx + size // 2
        lines += [f"      temp = yata_sword({work}[{a}]);", f"      {work}[{a}] = yata_add_mod({work}[{a}], {work}[{b}]);", f"      {work}[{b}] = yata_sub_mod(temp, {work}[{b}]);"]
    return lines


def y_emit_add_add(work: str, off: int, size: int) -> list[str]:
    lines = []
    for idx in range(size // 2):
        a = off + idx
        b = off + idx + size // 2
        lines += [f"      temp = yata_sword({work}[{a}]);", f"      {work}[{a}] = yata_add_mod({work}[{a}], {work}[{b}]);", f"      {work}[{b}] = temp - {work}[{b}];"]
    return lines


def y_emit_both_sredc(work: str, off: int, size: int) -> list[str]:
    lines = []
    for idx in range(size // 2):
        a = off + idx
        b = off + idx + size // 2
        lines += [f"      temp = {work}[{a}];", f"      {work}[{a}] = yata_sredc({work}[{a}] + {work}[{b}]);", f"      {work}[{b}] = yata_sredc(temp - {work}[{b}]);"]
    return lines


def y_emit_intt_r2(work: str, off: int, size: int) -> list[str]:
    lines = y_emit_add_add(work, off, size)
    lines += y_emit_both_mod(work, off, size // 2)
    block = size >> 2
    for j in range(block):
        idx = off + j + size // 2 + block
        lines.append(f"      {work}[{idx}] = yata_const_twiddle_mul({work}[{idx}], 2, 1);")
    lines += y_emit_both_sredc(work, off + size // 2, size // 2)
    return lines


def y_emit_intt_r3(work: str, off: int, size: int) -> list[str]:
    lines = y_emit_add_add(work, off, size)
    lines += y_emit_intt_r2(work, off, size // 2)
    block = size >> 3
    for i in range(block):
        lines.append(f"      {work}[{off + 2 * block + i + size // 2}] = yata_const_twiddle_mul({work}[{off + 2 * block + i + size // 2}], 3, 2);")
        lines.append(f"      temp = {work}[{off + i + size // 2}];")
        lines.append(f"      {work}[{off + i + size // 2}] = {work}[{off + i + size // 2}] + {work}[{off + 2 * block + i + size // 2}];")
        lines.append(f"      {work}[{off + 2 * block + i + size // 2}] = temp - {work}[{off + 2 * block + i + size // 2}];")
    for i in range(block):
        lines.append(f"      temp = yata_const_twiddle_mul({work}[{off + block + i + size // 2}], 3, 3);")
        lines.append(f"      {work}[{off + block + i + size // 2}] = yata_const_twiddle_mul({work}[{off + block + i + size // 2}], 3, 1) + yata_const_twiddle_mul({work}[{off + 3 * block + i + size // 2}], 3, 3);")
        lines.append(f"      {work}[{off + 3 * block + i + size // 2}] = temp + yata_const_twiddle_mul({work}[{off + 3 * block + i + size // 2}], 3, 1);")
    lines += y_emit_both_sredc(work, off + size // 2, size // 4)
    lines += y_emit_both_sredc(work, off + 3 * size // 4, size // 4)
    return lines


def y_emit_intt_transform(work: str, nbit: int, tables: dict[str, list[int]]) -> list[str]:
    lines: list[str] = []
    for sizebit in range(nbit, 3, -3):
        size = 1 << sizebit
        num_block = 1 << (nbit - sizebit)
        for block in range(num_block):
            off = size * block
            lines += y_emit_intt_r3(work, off, size)
            subblock = size >> 3
            for i in range(1, 8):
                stride = y_br3(i) * num_block
                table = "YATA_INTT_TABLE1" if i > 1 else "YATA_INTT_TABLE0"
                for idx in range(subblock):
                    lines.append(f"      {work}[{off + i * subblock + idx}] = yata_mul_sredc(yata_sword({work}[{off + i * subblock + idx}]), 27'sd{tables[table][stride * idx]});")
    final_blocks = 1 << (nbit - 3)
    for block in range(final_blocks):
        lines += y_emit_intt_r3(work, 8 * block, 8)
    return lines


def y_emit_ntt_r2(work: str, off: int, size: int, redc: bool) -> list[str]:
    lines = y_emit_both_mod(work, off, size // 2)
    lines += y_emit_both_mod(work, off + size // 2, size // 2)
    for idx in range(size // 4):
        a = off + idx
        b = off + idx + size // 2
        lines += [f"      temp = {work}[{a}];", f"      {work}[{a}] = yata_add_mod({work}[{a}], {work}[{b}]);", f"      {work}[{b}] = yata_sub_mod(temp, {work}[{b}]);"]
    for idx in range(size // 4, size // 2):
        a = off + idx
        b = off + idx + size // 2
        lines += [f"      temp = {work}[{a}];", f"      {work}[{b}] = -yata_const_twiddle_mul({work}[{b}], 2, 1);"]
        if redc:
            lines += [f"      {work}[{a}] = yata_sredc({work}[{a}] + {work}[{b}]);", f"      {work}[{b}] = yata_sredc(temp - {work}[{b}]);"]
        else:
            lines += [f"      {work}[{a}] = {work}[{a}] + {work}[{b}];", f"      {work}[{b}] = temp - {work}[{b}];"]
    return lines


def y_emit_ntt_r3(work: str, off: int, size: int) -> list[str]:
    lines = y_emit_ntt_r2(work, off, size // 2, False)
    lines += y_emit_both_mod(work, off + 2 * size // 4, size // 4)
    lines += y_emit_both_mod(work, off + 3 * size // 4, size // 4)
    block = size >> 3
    for idx in range(size // 2, size // 2 + block):
        lines += [f"      temp = {work}[{off + idx}];", f"      {work}[{off + idx}] = yata_add_mod({work}[{off + idx}], {work}[{off + idx + size // 4}]);", f"      {work}[{off + idx + size // 4}] = -yata_const_twiddle_mul(temp - {work}[{off + idx + size // 4}], 3, 2);"]
    for idx in range(size // 2 + block, size // 2 + 2 * block):
        lines += [f"      temp = -yata_const_twiddle_mul({work}[{off + idx}], 3, 1);", f"      {work}[{off + idx}] = -yata_const_twiddle_mul({work}[{off + idx}], 3, 3) - yata_const_twiddle_mul({work}[{off + idx + size // 4}], 3, 1);", f"      {work}[{off + idx + size // 4}] = temp - yata_const_twiddle_mul({work}[{off + idx + size // 4}], 3, 3);"]
    for idx in range(block):
        a = off + idx
        b = off + idx + size // 2
        lines += [f"      temp = yata_sword({work}[{a}]);", f"      {work}[{a}] = yata_add_mod({work}[{a}], {work}[{b}]);", f"      {work}[{b}] = yata_sub_mod(temp, {work}[{b}]);"]
    for i in range(1, 4):
        for idx in range(i * block, (i + 1) * block):
            a = off + idx
            b = off + idx + size // 2
            lines += [f"      temp = {work}[{a}];", f"      {work}[{a}] = yata_sredc({work}[{a}] + {work}[{b}]);", f"      {work}[{b}] = yata_sredc(temp - {work}[{b}]);"]
    return lines


def y_emit_ntt_transform(work: str, nbit: int, tables: dict[str, list[int]]) -> list[str]:
    lines: list[str] = []
    for block in range(1 << (nbit - 3)):
        lines += y_emit_ntt_r3(work, 8 * block, 8)
    for sizebit in range(6, nbit + 1, 3):
        size = 1 << sizebit
        num_block = 1 << (nbit - sizebit)
        block_size = size >> 3
        for block in range(num_block):
            off = size * block
            for i in range(8):
                stride = y_br3(i) * num_block
                suboff = off + i * block_size
                for idx in range(block_size):
                    table_is_1 = ((idx >> (sizebit - 6)) & 3) != 0
                    if stride == 0:
                        if table_is_1:
                            lines.append(f"      {work}[{suboff + idx}] = yata_mul_sredc(yata_sword({work}[{suboff + idx}]), 27'sd{SMALL.YATA_R2});")
                    else:
                        table = "YATA_NTT_TABLE1" if table_is_1 else "YATA_NTT_TABLE0"
                        lines.append(f"      {work}[{suboff + idx}] = yata_mul_sredc(yata_sword({work}[{suboff + idx}]), 27'sd{tables[table][stride * idx]});")
            lines += y_emit_ntt_r3(work, off, size)
    return lines


def generate_yata(variant: Any, top: str) -> str:
    n = variant.n
    lanes = variant.lanes
    cycles = variant.cycles
    tables = SMALL.generate_yata_tables(variant.nbit)
    arrays = "\n".join(
        f"      work[{i}] = yata_mul_sredc(intt_in_buf[{i}][26:0], 27'sd{tables['YATA_INTT_TWIST'][i]});"
        for i in range(n)
    )
    intt_body = arrays + "\n" + "\n".join(y_emit_intt_transform("work", variant.nbit, tables))
    ntt_init = "\n".join(f"      work[{i}] = $signed(ntt_in_buf[{i}]);" for i in range(n))
    ntt_body = ntt_init + "\n" + "\n".join(y_emit_ntt_transform("work", variant.nbit, tables))
    ports = [
        f"module {top}(",
        "  input clock,",
        "  input reset,",
        "  input io_intt_validin,",
        *lane_ports("io_intt_in", "input", 32, lanes),
        *lane_ports("io_intt_out", "output reg", 27, lanes),
        "  output reg io_intt_validout,",
        "  input io_ntt_validin,",
        *lane_ports("io_ntt_in", "input", 27, lanes),
        *lane_ports("io_ntt_out", "output reg", 32, lanes),
        "  output reg io_ntt_validout",
        ");",
    ]
    return banner("YATA datapath follows the RAINTT SREDC modular reduction style and intentionally avoids modulo operators.") + "\n".join(ports) + "\n" + textwrap.dedent(
        f"""\
          localparam integer YATA_N = {n};
          localparam integer YATA_CYCLES = {cycles};
          localparam signed [53:0] YATA_P = 54'sd{SMALL.YATA_P};
          localparam signed [63:0] YATA_MODSWITCH_SCALE = 64'sd{(1 << (32 + SMALL.YATA_WORDBITS - 1)) // SMALL.YATA_P};

          reg [31:0] intt_in_buf [0:YATA_N-1];
          reg signed [26:0] intt_out_buf [0:YATA_N-1];
          reg signed [26:0] ntt_in_buf [0:YATA_N-1];
          reg [31:0] ntt_out_buf [0:YATA_N-1];
          reg signed [53:0] work [0:YATA_N-1];
          reg [3:0] intt_in_count;
          reg [3:0] ntt_in_count;
          reg [3:0] intt_out_count;
          reg [3:0] ntt_out_count;
          reg intt_output_active;
          reg ntt_output_active;
          reg signed [53:0] temp;
          reg signed [26:0] mulres;
          reg [63:0] posres;
          reg [95:0] scaled;
          integer i;

          function automatic signed [26:0] yata_sword(input signed [53:0] x);
            begin
              yata_sword = x[26:0];
            end
          endfunction

          function automatic signed [26:0] yata_add_mod(input signed [53:0] a, input signed [53:0] b);
            reg signed [53:0] add;
            begin
              add = a + b;
              if (add >= YATA_P) yata_add_mod = add - YATA_P;
              else if (add <= -YATA_P) yata_add_mod = add + YATA_P;
              else yata_add_mod = add;
            end
          endfunction

          function automatic signed [26:0] yata_sub_mod(input signed [53:0] a, input signed [53:0] b);
            reg signed [53:0] sub;
            begin
              sub = a - b;
              if (sub >= YATA_P) yata_sub_mod = sub - YATA_P;
              else if (sub <= -YATA_P) yata_sub_mod = sub + YATA_P;
              else yata_sub_mod = sub;
            end
          endfunction

          function automatic signed [26:0] yata_sredc(input signed [53:0] a);
            reg [26:0] a0;
            reg signed [26:0] a1;
            reg signed [26:0] m;
            reg signed [26:0] t1;
            reg signed [53:0] m_wide;
            reg signed [53:0] t1_wide;
            begin
              a0 = a[26:0];
              a1 = a[53:27];
              m_wide = -(({{27'd0, a0}} * 54'sd{SMALL.YATA_K}) <<< {SMALL.YATA_SHIFTAMOUNT}) + {{27'd0, a0}};
              m = m_wide[26:0];
              t1_wide = (($signed(m) * 54'sd{SMALL.YATA_K}) <<< {SMALL.YATA_SHIFTAMOUNT}) + $signed(m);
              t1 = t1_wide[53:27];
              yata_sredc = a1 - t1;
            end
          endfunction

          function automatic signed [26:0] yata_mul_sredc(input signed [26:0] a, input signed [26:0] b);
            begin
              yata_mul_sredc = yata_sredc($signed(a) * $signed(b));
            end
          endfunction

          function automatic signed [53:0] yata_const_twiddle_mul(input signed [53:0] a, input integer radixbit, input integer num);
            begin
              if (radixbit == 2 && num == 1) yata_const_twiddle_mul = (a * 25) <<< 8;
              else if (radixbit == 3 && num == 1) yata_const_twiddle_mul = (a * 5) <<< 4;
              else if (radixbit == 3 && num == 2) yata_const_twiddle_mul = (a * 25) <<< 8;
              else if (radixbit == 3 && num == 3) yata_const_twiddle_mul = (a * 125) <<< 12;
              else yata_const_twiddle_mul = a;
            end
          endfunction

          task automatic compute_intt;
            begin
        {intt_body}
              for (i = 0; i < YATA_N; i = i + 1) intt_out_buf[i] <= work[i][26:0];
            end
          endtask

          task automatic compute_ntt;
            begin
        {ntt_body}
        """
    ) + "\n".join(
        [
            f"        mulres = yata_mul_sredc(yata_sword(work[{i}]), 27'sd{tables['YATA_NTT_TWIST'][i]});\n"
            f"        posres = (mulres < 0) ? (mulres + YATA_P) : mulres;\n"
            f"        scaled = ((posres * YATA_MODSWITCH_SCALE) + 96'd{1 << (SMALL.YATA_WORDBITS - 2)}) >> {SMALL.YATA_WORDBITS - 1};\n"
            f"        ntt_out_buf[{i}] <= scaled[31:0];"
            for i in range(n)
        ]
    ) + textwrap.dedent(
        """
            end
          endtask

          always @(posedge clock) begin
            if (reset) begin
              io_intt_validout <= 1'b0;
              io_ntt_validout <= 1'b0;
              intt_in_count <= 4'd0;
              ntt_in_count <= 4'd0;
              intt_out_count <= 4'd0;
              ntt_out_count <= 4'd0;
              intt_output_active <= 1'b0;
              ntt_output_active <= 1'b0;
              for (i = 0; i < YATA_N; i = i + 1) begin
                intt_in_buf[i] <= 32'd0;
                intt_out_buf[i] <= 27'sd0;
                ntt_in_buf[i] <= 27'sd0;
                ntt_out_buf[i] <= 32'd0;
              end
            end else begin
              io_intt_validout <= 1'b0;
              io_ntt_validout <= 1'b0;

              if (intt_output_active) begin
                io_intt_validout <= 1'b1;
        """
    ) + "\n".join(
        f"        io_intt_out_{lane} <= intt_out_buf[intt_out_count * {lanes} + {lane}];"
        for lane in range(lanes)
    ) + textwrap.dedent(
        f"""
                if (intt_out_count == YATA_CYCLES - 1) begin
                  intt_output_active <= 1'b0;
                  intt_out_count <= 4'd0;
                end else begin
                  intt_out_count <= intt_out_count + 1'b1;
                end
              end

              if (ntt_output_active) begin
                io_ntt_validout <= 1'b1;
        """
    ) + "\n".join(
        f"        io_ntt_out_{lane} <= ntt_out_buf[{lane} * YATA_CYCLES + ntt_out_count];"
        for lane in range(lanes)
    ) + textwrap.dedent(
        f"""
                if (ntt_out_count == YATA_CYCLES - 1) begin
                  ntt_output_active <= 1'b0;
                  ntt_out_count <= 4'd0;
                end else begin
                  ntt_out_count <= ntt_out_count + 1'b1;
                end
              end

              if (io_intt_validin) begin
        """
    ) + "\n".join(
        f"        intt_in_buf[{lane} * YATA_CYCLES + intt_in_count] = io_intt_in_{lane};"
        for lane in range(lanes)
    ) + textwrap.dedent(
        """
                if (intt_in_count == YATA_CYCLES - 1) begin
                  intt_in_count <= 4'd0;
                  compute_intt();
                  intt_output_active <= 1'b1;
                  intt_out_count <= 4'd0;
                end else begin
                  intt_in_count <= intt_in_count + 1'b1;
                end
              end

              if (io_ntt_validin) begin
        """
    ) + "\n".join(
        f"        ntt_in_buf[ntt_in_count * {lanes} + {lane}] = io_ntt_in_{lane};"
        for lane in range(lanes)
    ) + textwrap.dedent(
        """
                if (ntt_in_count == YATA_CYCLES - 1) begin
                  ntt_in_count <= 4'd0;
                  compute_ntt();
                  ntt_output_active <= 1'b1;
                  ntt_out_count <= 4'd0;
                end else begin
                  ntt_in_count <= ntt_in_count + 1'b1;
                end
              end
            end
          end
        endmodule
        """
    )


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    files = {
        "SmallHoge32P64Rtl.sv": generate_hoge32(),
        "SmallYata8RainttP27Rtl.sv": generate_yata(SMALL.VARIANTS["yata8"], "SmallYata8RainttP27Rtl"),
        "SmallYata8x8RainttP27Rtl.sv": generate_yata(SMALL.VARIANTS["yata8x8"], "SmallYata8x8RainttP27Rtl"),
    }
    for filename, content in files.items():
        path = OUT_DIR / filename
        path.write_text(content, encoding="utf-8")
        print(path.relative_to(REPO_ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
